### ISSUE TITLE
Code Documentation File

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#104]
This was mentioned a couple weeks ago, but wanted to revive it.  Basic PDF summary of key commands to be written at a later date.

**Comment by bqpd** [comment]
@cjk12, what are your thoughts on this now that we have sphinx up and running?

**Comment by whoburg** [comment]
Related issue: https://github.com/convexopt/gpkit/issues/139

**Comment by cjk12** [comment]
I'm pretty happy with what I've seen so far.  I think we can close this
issue.
