### ISSUE TITLE
Variable Function vs. Mon and Vecmon

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#109]
I think that variable declarations should be done with some type of specific variable function and not mon and vecmon.  We could potentially also have a vecvar function that would support vector variables in addition to vector capability in the variable function.  Open to discussion.

**Comment by whoburg** [comment]
We are implementing option 1. Changes:

* Rename `Variable` to `VarKey`
Added cosmetic class `Variable` which inherits from `Monomial` and has no other features (implements the former `mon`).
Added cosmetic class `VectorVariable`, which inherits from `PosyArray` and has no other features (implements the former `vecmon`).
