### ISSUE TITLE
Version 0.0 Publication Date

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#110]
I would like to request that Version 0.0 be out sometime in mid-January.  Any thoughts on a potential hard deadline of 2/1/15?  I'd really like to be developing on a stable version of the code when the AHS paper is winding down.  At the latest, we need to have 0.0 out by 3/16/15 (due date for AHS Papers).

**Comment by whoburg** [comment]
We will release the initial version before COB Friday, January 23, 2015.
