### ISSUE TITLE
Should Constraint objects have units?

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#113]
This might be really dumb, but I'm wondering whether `Constraint` objects should really have units. Since the standard GP form is to move everything to one side and set ` == 1` or `<= 1`, I'm wondering why constraints aren't always unit-less.

**Comment by whoburg** [comment]
Current design:

* `Constraint` inherits from `Posynomial`
* Constraint objects additionally have two `Posynomial` attributes, `self.left` and `self.right`, which are used for printing prettily.
* Units are kept around for the left and right sides, but these are enforced to be equal in the `__init__`

**Comment by whoburg** [comment]
Open question: should `Constraint` objects keep around this extra user-specified structure, or simply force default to standard GP form (1 >= on one side of all constraints)?

Argument for keeping structure:
Could be much nicer for printing. Could add a method for converting to standard form. Already implemented this way.

Argument for defaulting to standard form:
Simplicity of source code and unit tests.

**Comment by bqpd** [comment]
I'm in favour of keeping the structure. Who's opposed? We were talking about making this an optional setting, though that could be potentially confusing...

**Comment by whoburg** [comment]
Let's release with the current structure, and we can revisit if anyone encounters an example or application where unit-ed `Constraint`s create confusion. We can close this if there are no objections by, say, noon.

**Comment by bqpd** [comment]
And so it was.

**Comment by whoburg** [comment]
And they lived happily ever after.
