### ISSUE TITLE
Variable type for solved variables is a character array

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#115]
Related to issue #114 

`import gpkit as gpkit`
`A = gpkit.mon("A", "-", "Test Variable")`
`gp = gpkit.GP(A, [A>=1])`
`res_all = gp.solve(printing=False)`
`res = res_all['variables']`
`print type(res['A'])`

returns:
`<type 'numpy.ndarray'>`

Should this be a float rather than a character array?

**Comment by bqpd** [comment]
I think it's a 0-D array, which follows numpy convention; what is
`res['A'].shape`?

**Comment by whoburg** [comment]
```
In [6]: print type(res['A'])
<type 'numpy.ndarray'>

In [7]: res['A'].shape
Out[7]: ()

In [8]: res['A']
Out[8]: array(1.0)

In [9]: res['A'].dtype
Out[9]: dtype('float64')
```

**Comment by whoburg** [comment]
@cjk12, what's making you believe it's a character array?

**Comment by cjk12** [comment]
I think I was confused by the ndarray thing.  When I went to print A, I had
to convert it to a float and then it printed fine.  Do I need to call
`res['A'][0]`?  I thought we eliminated that from the code...

**Comment by bqpd** [comment]
So, this is a place where we're following the numpy convention with 0-d
arrays, which act like floats in _almost_ all situations. Whenever a 0-d
array doesn't act like a float, though, it makes me very sad, because they
act very little like n-d arrays: for example, `res['A'][0]` will return an
error. :-/

I'm ambivalent on this, but if the 0-d arrays aren't printing properly then
I think we should return floats instead.

**Comment by cjk12** [comment]
It isn't a huge deal, although, I have to add a line of code for each
variable I attempt to print (could well be in the ballpark of 20 by the
time I'm done since I'm printing results to an output file).
Alternatively, if there is convention for printing 0-d arrays, that might
work.  I'd probably prefer floats, but sticking with convention also
definitely has perks...

**Comment by bqpd** [comment]
What's your code to print them? This, for example, should work well:
```print "This is the area: %f" % res['A']```

**Comment by cjk12** [comment]
`f.write('Rotor Area \t\t\t\t\t|\t {0:.3f} \t m^2\n'.format(res['A']))`

I want to have more control over where things line up, hence the
complicated text manipulation.  I'm basically making a table.  I will
acknowledge this may not be the best way, but I looked through a few
different options and this was the one that did what I wanted.

**Comment by bqpd** [comment]
That code works fine for me; I believe format casts automatically to a
float?

**Comment by cjk12** [comment]
I was getting an error until I added the line:

`res['A']=np.float(res['A'])`

Let me see if I can boil it down in the context of the simple test and get
back to you in a little bit.

**Comment by bqpd** [comment]
Does `res.subinto(A)` give you a float?

**Comment by whoburg** [comment]
The result of this ticket will be a unit test

**Comment by bqpd** [comment]
Documented in the new best practices box.

**Comment by whoburg** [comment]
Added unit test in 81025a3bb5d24ca831113e79ca055da583fdac35
