### ISSUE TITLE
Document and test: what exactly does it mean to set value= for a Variable?

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#124]
From https://github.com/convexopt/gpkit/issues/93, it's possible to declare the value of a constant at the same time as you declare the constant, with syntax like

```python
rho = gpkit.Variable("\rho", value=1.2, units="kg/m^3")
```

Document exactly what behavior this syntax implements. Unit test that the return type is `Variable`. Unit test that the 1.2 value is stored in the expected attribute. Unit test any other expected behavior known by @bqpd.

**Comment by bqpd** [comment]
http://gpkit.readthedocs.org/en/latest/basiccommands.html#declaring-variables could be a good place to do this.

**Comment by whoburg** [comment]
And in the docstrings. In the above, should `Monomial` be changed to `Variable` according to our best practices?

Current docstrings:

* `Posynomial`: does not mention `value=` kwarg
* `Monomial`: empty
* `Variable`: looks good; mentions `value=`

**Comment by bqpd** [comment]
Yeah, that sounds right! Do you think Posy/Monomial should mention `value=`, considering that it doesn't always work with them?

**Comment by whoburg** [comment]
re: Posy/Monomial mentioning `value=`, no -- if it doesn't always work with them, I think we should limit use of that keyword argument to `Variable`. I changed the original ticket text accordingly. We should add some unit tests to `t_vars.py` before closing this ticket.

**Comment by bqpd** [comment]
There are now several tests for this in `t_subs.py`
