### ISSUE TITLE
Documentation: best practices

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#127]
Priority

**Comment by bqpd** [comment]
I made a probably overcomplicated but at least exhaustive [Box example](http://nbviewer.ipython.org/github/convexopt/gpkit/blob/master/gpkit/examples/Box/Box.ipynb) which covers substitution, sweeping, interactive widgets, accessing variables from a solution, and so on. Basically everything but vector variables.

**Comment by bqpd** [comment]
Check it out for the JS widget if nothing else! Feedback on formatting / readability greatly appreciated.

Known bugs:
  * the form of an optimization problem is not introduced, but probably should be
  * it's never explicitly mentioned that the interactive graphic represents an unfolded box

**Comment by bqpd** [comment]
Is this ticket closable?

**Comment by whoburg** [comment]
Broken link to "Box" above should be updated. And some or all of these best practices need to be put in the "Basic Commands" documentation section, but that is covered by https://github.com/convexopt/gpkit/issues/139.

**Comment by bqpd** [comment]
Link fixed.
