### ISSUE TITLE
Documentation: citing gpkit

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#128]
Propose putting bibtex info etc on front page

**Comment by bqpd** [comment]
Some potentially useful links:

http://superuser.com/questions/8743/how-to-cite-software-in-latex

http://tex.stackexchange.com/questions/90019/how-to-cite-sourcecode-from-an-svn-repository

**Comment by whoburg** [comment]
Is sphinx able to create a PDF “user manual” for us? We could post that, thereby giving us a manual to cite.

**Comment by whoburg** [comment]
Is sphinx able to create a PDF “user manual” for us? We could post that, thereby giving us a manual to cite. 

-----------------------------------------------------------
Warren Hoburg
Boeing Assistant Professor
Department of Aeronautics and Astronautics
Massachusetts Institute of Technology
77 Massachusetts Ave, 33-404
Cambridge, MA 02139
Phone: 617-253-1207

**Comment by bqpd** [comment]
Closed by 82e672e4431a698b314467bb8629823e90b0bcb4 and my commit which copies that text to the readme

**Comment by whoburg** [comment]
I tweaked the bibtex earlier in ddb922669a010d779e20ed8b8e21f8f92c720cae. This means that the README and setup.py now disagree with http://gpkit.readthedocs.org/en/latest/citinggpkit.html. What's the least-impact fix now that we've released?

Sorry...

**Comment by bqpd** [comment]
Looks like I copied your updated text. :)

**Comment by bqpd** [comment]
Nevermind, @pgkirsch did that. :p

**Comment by pgkirsch** [comment]
Oops...sorry for not consulting this issue whilst making the edits...

I just noticed a discrepancy and assumed it was accidental. Hope it didn't mess anything up.

**Comment by whoburg** [comment]
Fixed more minor discrepancies in 372c417fe5bc888668a15367fc04ae7add179287. Is there a clever way we can avoid having three separate copies of the citation bibtex (in README, setup.py, and on readthedocs)? I'm tempted to delete the README one, since it already explicitly links to the citation instructions on readthedocs.

**Comment by bqpd** [comment]
Let's remove it from the README and setup, then.

**Comment by pgkirsch** [comment]
Agreed

**Comment by bqpd** [comment]
It is so.
