### ISSUE TITLE
pint warning message and installation

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#129]
For anyone who doesn't have pint installed, the first message seen when running things in GP is:

```
>>> import gpkit
Unable to load pint; unit support disabled.
```

Currently it looks like an installation error and might make a user concerned that they have done something wrong. The obvious solution is perhaps to require people to install `pint`. The README makes this step seem optional, which I think is completely fine. But if it is truly optional, then I don't believe that the above message should print..or at least it should be rephrased.. 

The fix for this could be one or more of the following:
- Rephrase the message to appear less like an error. This is still an issue for me just because someone who never intends to use unit support doesn't want to see the message at all.
- Modify the README to require `pint` installation. For the record I appreciate why it has been phrased as optional - no one likes to install more than they need - but imo the bare minimum correct installation should not have any more error-like messages than the most comprehensive installation. This solution could be perceived as deceptive by anyone familiar with `pint`.... "if they are making me install `pint` for bare bones GP solving, what other extraneous crap have they put on my machine".

Open to other (see: better) solutions though.

**Comment by whoburg** [comment]
I like option 1 -- keep pint optional.

@pgkirsch, can you craft a suggested rephrasing?

**Comment by whoburg** [comment]
Something like "pint is not installed; unit support disabled" ?

**Comment by pgkirsch** [comment]
I was actually just typing an add-on, arguing that the current message is a little misleading/ambiguous. Units are supported to an extent without `pint`: a user can declare units for a given variable and these units will print to the results table etc..

Maybe I'm too much in the user-hand-holding camp, but if I don't know what pint is, or what it does (actually true for me), then I would at least like to know more about how I am limited by not having pint. Although, one could argue this goes in docs...

I'll work on another possible suggestion.

**Comment by pgkirsch** [comment]
` "Optional python units library (pint) not installed; unit support disabled."`

**Comment by bqpd** [comment]
Nice, this looks good.
