### ISSUE TITLE
Unable to import expopt

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#130]
```python
import gpkit as gpkit
A = gpkit.Variable("A", "-", "Test Variable")
gp = gpkit.GP(A, [A>=1.3])
sol = gp.solve(printing=False)
```

Is now returning error:
"cannot import name expopt"

**Comment by bqpd** [comment]
Hmm, this also works fine for me...

**Comment by cjk12** [comment]
Ok, along with issue #132 , I will simply be coding my examples as I know they should run and ignoring all errors until tomorrow...

**Comment by cjk12** [comment]
Started working this morning.
