### ISSUE TITLE
Documentation: Disabling Units with pint Installed

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#131]
Somewhat related to #129 , do we have a method of disabling units when pint  is installed?

**Comment by bqpd** [comment]
oops, yes. `gpkit.disableUnits()`, as seen in `tests/simpleflight_nounits.py`

**Comment by whoburg** [comment]
Is that documented yet?

**Comment by bqpd** [comment]
Nope!

**Comment by whoburg** [comment]
This is documented in the glossary, which is sufficient. I recall, however, that there are some tricky points about importing `gpkit` multiple times, which we encountered in the unit tests. If I'm right about that, can we clarify how it all works?
