### ISSUE TITLE
Units not coming into VectorVariable Correctly

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#132]
The following:

```python
import gpkit as gpkit
d   = gpkit.VectorVariable(3, "d", "m", "Dimension Vector")
```

is returning:
`ValueError: units must be either a string or a Quantity from gpkit.units.`

**Comment by bqpd** [comment]
Hmm, that works for me. Probably a bug with the string-to-units conversion that's somehow occurred in your setup.

**Comment by cjk12** [comment]
Started working this morning.
