### ISSUE TITLE
Should arithmetic operations on VectorVariable cast to PosyArray?

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#136]
Currently, arithmetic operations on `Variable` objects return `Monomial` objects. In contrast, arithmetic operations on `VectorVariable` objects return `VectorVariable` objects:

```python
In [1]: from gpkit import VectorVariable
Optional Python units library (Pint) not installed; unit support disabled.

In [2]: v = VectorVariable(3, 'v')

In [3]: type(3*v)
Out[3]: gpkit.nomials.VectorVariable
```

Is this what we want?

**Comment by bqpd** [comment]
Oh shoot, I forgot that that's how ndarrays work. :-/

**Comment by bqpd** [comment]
I think the best way to fix this might be to have VectorVariable be a function that returns a posyarray.

**Comment by bqpd** [comment]
Fixed-ish: VectorVariable is still a class, but now magically creates a PosyArray.
