### ISSUE TITLE
Substitution (value arg) for VectorVariable

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#137]
The following:

```python
x_arr = np.arange(0, length, length/N)+1e-6
x 	  = gpkit.VectorVariable(N, "x", x_arr, "m", "Beam Location")
```

Returns an error:
`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

Seems like this should work...

**Comment by cjk12** [comment]
Also needs unit test

**Comment by bqpd** [comment]
This is supposed to work, checking...

**Comment by whoburg** [comment]
I'm going to add a unit test
