### ISSUE TITLE
Documentation: basic commands missing

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#139]

**Comment by bqpd** [comment]
Moved basic commands into "getting started" as part of an outline reorg. Feel free to move it back!

**Comment by whoburg** [comment]
Looks good. Proposal: move "Basic commands" above "Writing GPkit scripts". Reasoning is that this ordering will feel more logical for most users.

**Comment by whoburg** [comment]
I'm having second thoughts on ordering. Currently, [Getting Started](http://gpkit.readthedocs.org/en/latest/gettingstarted.html) basically tells you to install gpkit, and links to the install instructions page. Since Basic Commands is a really important section, I think it makes sense for it to come after installation instructions (so that clicking "next" after installation brings you to basic commands).

**Comment by bqpd** [comment]
Hmm, but if Getting Started is just telling you to install...why not
"Install" => "Getting Started"? (with basic commands still in "Getting
Started")

**Comment by whoburg** [comment]
Yes, I'm happy with that order. Currently, getting started is also our "easing in" for non-python and non-command line users, so we'll have to figure out where that material belongs. Could go in install instructions.

**Comment by bqpd** [comment]
Order changed in newest docs!

**Comment by pgkirsch** [comment]
Still lacking basic commands...at least until I figure out how to get readthedocs to update...

**Comment by pgkirsch** [comment]
@bqpd  I'd like to move "basic commands" back out of "getting started" if that's ok with you (and put it directly after)

**Comment by bqpd** [comment]
Sounds fine to me.

**Comment by pgkirsch** [comment]
Cool, thanks. Do I need to do anything besides creating the .rst and adding it to the toctree in index.rst? It didn’t seem to be working quite right when I was playing around earlier.




On Jan 26, 2015, at 01:36 AM, bqpd <notifications@github.com<mailto:notifications@github.com>> wrote:

Sounds fine to me.

**Comment by bqpd** [comment]
Hmm, that should be all that's needed.

**Comment by whoburg** [comment]
Basic commands update and improved in eec4e487342ff296082a5236324fda75e1277820.
