### ISSUE TITLE
Link documentation to latest release instead of bleeding edge

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#140]

**Comment by bqpd** [comment]
We can't do this until we release...

**Comment by whoburg** [comment]
Where should this link go in the documentation? We could link to https://github.com/convexopt/gpkit/releases/latest.

**Comment by whoburg** [comment]
Also, do we need to update the install script and/or the install instructions, which currently suggest running

```python
pip install https://github.com/convexopt/gpkit/zipball/master
```
?

**Comment by bqpd** [comment]
Yup, on it.

**Comment by bqpd** [comment]
Aaaand, got this working: `pip install gpkit`
