### ISSUE TITLE
remove matlab code?

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#142]
It doesn't seem to be doing much in the repo at present; probably better for the lab dropbox? Not my call, though. @convexopt/developers

**Comment by whoburg** [comment]
I agree. The matlab code should not be part of the release. Further, we haven't updated the matlab code much if at all, so we won't lose any version controlled history. Took the following actions:

* moved matlab code to group dropbox folder
* removed `matlab` directory from gpkit
