### ISSUE TITLE
Test and document the Constraint class as applied to Signomials

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#143]
also `MonoEQConstraint`

**Comment by whoburg** [comment]
Added a couple `Constraint` tests in c97b6e430744bae6841b96b0df2d4f52f2ceba8d, but we need more before this can be closed.

**Comment by whoburg** [comment]
Added a MonoEQConstraint test in 1602b7697f17818ecedb324fed4115154f1d31c1.

`Constraint` initialization and subclassing are kind of a mess right now 
 - [ ] `Constraint` inherits from `Posynomial`, but doesn't call `super`
 - [ ] `MonoEQConstraints` are instances of `Posynomial` but not `Monomial`
 - [ ] Constraints involving Signomials are not well documented, and I worry too much of the simplification logic is currently in `nomials.py` when some of it (like what to move to what side) should perhaps live in a solution heuristic. In any case, the any approach needs documentation.

We do have some documentation and testing in place for non-Signomials. Therefore, I propose renaming this and changing the milestone, keeping it open. That's done -- feel free to change back to 0.2.0 if anyone disagrees.

**Comment by bqpd** [comment]
Sounds good to me.

**Comment by whoburg** [comment]
Addressed by #360
