### ISSUE TITLE
best practices: classes to import in __init__.py

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#144]
Here's what we currently import in gpkit's `__init__.py`:

```python
from .nomials import Monomial, Posynomial, Variable, VectorVariable, VarKey
from .posyarray import PosyArray
from .geometric_program import GP
```

According to our suggested best practices, should users ever interact with `VarKey` or `PosyArray`? If not, I propose removing their imports from the `__init__.py`.

It could even be argued that `Monomial` and `Posynomial` can be removed, since they are generally created via operator overloading, but that might be a bit too extreme.

**Comment by bqpd** [comment]
My thinking there was that every variable that you could expect to see
printed (a la "gpkit.Monomial(x)" etc.) should be importable with the same
syntax as it's printed with.

**Comment by whoburg** [comment]
Understood. Do we ever expect to see `VarKey` printed? What about `PosyArray`?

And while we're talking about these, what about `GPSolutionArray` and `Constraint`?

**Comment by bqpd** [comment]
If they look at solution.keys(), then they would.

Hmm, yeah, Constraint is a counterexample.

I don't think I care much one way or the other.

**Comment by bqpd** [comment]
It looks like `__init__` needs PosyArray to fix up pints, so I'm inclined to leave this as is.

**Comment by whoburg** [comment]
Ok, leaving as is.
