### ISSUE TITLE
Make an exciting example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#147]
Make a really exciting example to impress busy readers. Bonus points for being educational. Could place graphic/screenshot from this example on the [Documentation homepage](http://gpkit.readthedocs.org/en/latest/).

Ideas:
* Aircraft design?
* motor model?
* Circuit design?

Related issues: 
https://github.com/convexopt/gpkit/issues/42 (more examples)
https://github.com/convexopt/gpkit/issues/148 (aircraft design example)

**Comment by bqpd** [comment]
We seem to be creating new issues for each idea of a neat example, so perhaps this issue could be closed?

**Comment by whoburg** [comment]
Yeah, I think this is probably superseded by #148.
