### ISSUE TITLE
Write a step-by-step aircraft design example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#148]
Educational example that steps through aircraft design models, building up from very simple to increasingly complex.

**Comment by cjk12** [comment]
I can work on this this week, however, it may lack @bqpd's special touches...

**Comment by bqpd** [comment]
I made a quick [fuel / range example](http://nbviewer.ipython.org/github/convexopt/gpkit/blob/master/docs/source/ipynb/Fuel/Fuel.ipynb) with the interactive web widgets: not sure where it fits on the complexity scale, though. :)

**Comment by bqpd** [comment]
With the new [modular](http://nbviewer.ipython.org/github/convexopt/gpkit/blob/master/docs/source/ipynb/modular/modular.ipynb) example we've got a nicer framework for incremental complexity!

**Comment by bqpd** [comment]
Should this be in gpkit-model?

**Comment by whoburg** [comment]
yes.

**Comment by bqpd** [comment]
Moved to https://github.com/aeroa/gpkit-models/issues/7
