### ISSUE TITLE
initial release version number

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#149]
According to http://semver.org, our initial release should be version 0.1.0. Any objections to making it so?

**Comment by bqpd** [comment]
Not here!

**Comment by whoburg** [comment]
It will be so. In anyone objects, re-open this.

**Comment by whoburg** [comment]
@bqpd, I changed the name of the milestone to 0.1.0. Are there any other places we need to change this?

**Comment by bqpd** [comment]
Nope! Such is the magic of pypi: we'll just push version 0.1.0 when ready
