### ISSUE TITLE
Add examples into GP 101

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#150]
Add non-mathy examples into "What is a GP?"  Not for version 0.1.0

**Comment by cjk12** [comment]
Added examples and pushed update.  Open to feedback.

**Comment by bqpd** [comment]
Nice, that looks good to me.

  * in the posynomials, should it maybe be 0.56 instead of .56?
  * Should it be mentioned that all monomials are also posynomials?

**Comment by cjk12** [comment]
0.56 should be updated now.

Yea, I can do that.

**Comment by cjk12** [comment]
Added a one sentence description, should be up shortly.  @whoburg any more thoughts before we close the issue?

**Comment by whoburg** [comment]
Looks great. I made a couple minor tweaks in f2af087957f188d7c5f12a9816852629c5cb4236. Closing the issue, but feel free to continue tweaking/improving.
