### ISSUE TITLE
Further Detail GPkit Special Features

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#152]
Include Pareto Frontiers, plots of design spaces, etc...  Likely for version 1.0.0

**Comment by whoburg** [comment]
Sweeps, etc. Put here: http://gpkit.readthedocs.org/en/latest/basiccommands.html

**Comment by bqpd** [comment]
Putting the new "Feature of the Week" emails in an Advanced Commands section; request a particular topic in this thread.

**Comment by bqpd** [comment]
Added sweeps to http://gpkit.readthedocs.org/en/latest/advancedcommands.html

**Comment by whoburg** [comment]
Awesome!

**Comment by bqpd** [comment]
Added substitutions.

**Comment by bqpd** [comment]
Added Signomial Programming. I think interactive widgets is the only advanced feature that remains.

**Comment by bqpd** [comment]
+ sensitivities

**Comment by bqpd** [comment]
+ accessing stuff from sweeps

**Comment by bqpd** [comment]
Sensitivity info on #179
MOO discussion on #181

**Comment by bqpd** [comment]
The last three unchecked on this last are milestone 0.3

The first unchecked one is 0.4

I'll write up a sensitivities section and move this to 0.3!

**Comment by bqpd** [comment]
Superseded by #332
