### ISSUE TITLE
GPSolutionArray.table() formatting issues

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#153]
At the very least, the order of `15.588 : Cost` should be flipped.

```python
In [38]: print sol.table()
    15.588 : Cost
           | Free variables
         x : 0.577    [m]
         y : 0.289    [m]
         z : 0.385    [m]
           |
           | Constants
         S : 1        [m^2]
           |
           | Constant sensitivities
         S : -1.5     [-]
           |
```

**Comment by bqpd** [comment]
Ack. The problem is that when you print the table for a sweep, it says "Cost (average of N sweeps)", which won't fit on the left side of the divider.

**Comment by whoburg** [comment]
Could we make Cost a header, like Free Variables, Constants, and Constant sensitivities?
