### ISSUE TITLE
history of changes

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#154]
We need a way to track what's changed version-to-version. How should we do this?

**Comment by whoburg** [comment]
Related: should the documentation have a list of releases somewhere?

**Comment by bqpd** [comment]
It does! here: https://readthedocs.org/projects/gpkit/ and in the menu on
the left side of http://gpkit.rtfd.org

**Comment by whoburg** [comment]
Ah, nice. Ok, so then the only remaining question is the original one.

**Comment by bqpd** [comment]
Probably a new sphinx pages? Maybe called Version Changes?

**Comment by whoburg** [comment]
Changelist link: http://gpkit.readthedocs.org/en/latest/releasenotes.html

**Comment by whoburg** [comment]
Reopening this for 0.2.0. Before release, copy release notes from here: https://github.com/convexopt/gpkit/releases to here: http://gpkit.readthedocs.org/en/latest/releasenotes.html.

**Comment by bqpd** [comment]
(good plan)

**Comment by whoburg** [comment]
(Duplicate of #210)
