### ISSUE TITLE
Appending to the Solutions Structure

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#155]
We currently have it set up so that:

```python
sol(A)
```

calls the design variable A out of the solution structure.  However, when I go to compute calculated variables, it is natural for me to want to say

```python
sol(B)=sol(A)**2
```

Where here B is a field I am creating.   This currently spits out the error:

```python
"SyntaxError: can't assign to function call"
```

However, the line

```python
sol['B'] = sol['A']**2
```

works exactly as expected.  It would be nice if the standard parenthesis notation did what this last line does.

**Comment by whoburg** [comment]
I don't think that's going to be possible in Python.

Backing up a little, what's the reason for wanting to mutate the solution? Why not just assign

```python
B = sol(A)**2
```

Or, alternatively,

```python
computed_quantities = {}
computed_quantities['B'] = sol(A)**2
```

**Comment by cjk12** [comment]
On the first one, it's easier to pass a data structure between files than many variables.

On the second one, I want to be able to treat B and A equally in later parts of the code rather than calling two different structures to access one or the other.  Not terribly important, but saves some typing and the handling of an additional data structure.  We can chat about this later if this is poor practice.  I'll close the issue for now.

**Comment by bqpd** [comment]
Hmm, interesting. Does mutating `sol["variables"]` work well for your use
case? Or how about just declaring `B == A**2` as a monomial inequality?
(shouldn't slow down the solve much and makes the model structure more
explicit...)

**Comment by cjk12** [comment]
Yea, it works, but its more typing than just ().  So, in terms of bringing
it into the GP, one of the most frustrating things I have run into is the
fact that carrying around too many variables results in mosek returning
UNKNOWN, which basically means it found a solution, but one variable is
free, so mosek just quits.  The way I fight this is by only keeping the
variables necessary to converge the optimization in my GP.  That also helps
me figure out what variables are crucial in my optimization and what have
no effect on the final result.  So my decision there has nothing to do with
solve time.

**Comment by bqpd** [comment]
Oh, interesting!

(also, you could say `sold = dict(sol["variables"])` or something to that
effect to make an unlinked copy of the variables dictionary)

**Comment by whoburg** [comment]
@cjk12, do you have a simple example of the free variable / UNKNOWN issue you mentioned? That sounds like a good unit test, or maybe something to bring to the attention of mosek if we think the solver is behaving incorrectly.

**Comment by cjk12** [comment]
It's not a problem with mosek, it's just a decision they made with the
solver.  I'll post a really simple example here shortly.  Don't think it
can be unit tested because it's internal to mosek.  It showed up in the
matlab too.

**Comment by cjk12** [comment]
So of course now that I've raised the issue, I can't mimic the behavior.  I'll post again here when I return Unknown again.  Should be soon, as it happens quite regularly.

**Comment by whoburg** [comment]
Great, and since this is off-topic from the original ticket, maybe open a new ticket and link it here.
