### ISSUE TITLE
free_variables vs. variables

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#156]
In the solution array, what is the difference between free_variables and variables?  They seem to be redundant...

**Comment by bqpd** [comment]
free_variables shouldn't include constants.

**Comment by cjk12** [comment]
Ah, thanks.

**Comment by cjk12** [comment]
This needs to be reevaluated.  As of now, my Rotor code is returning very different results for variables and free variables, as in one makes sense and one is completely wrong.  I will try to post an example, but it may take a while for me to boil down what is going on.  Figured I'd give @bqpd a head start.

**Comment by cjk12** [comment]
Never mind.
