### ISSUE TITLE
Evaluation of Mosek UNKNOWN Return

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#157]
Continuation from issue #155  to evaluate what Mosek is returning with an UNKNOWN response.

**Comment by bqpd** [comment]
Has this happened again / yet?

**Comment by cjk12** [comment]
Yea, I've gotten it, but have failed to solidify the root cause.  I believe this to be a low priority, but will post here when I have identified the cause.

**Comment by whoburg** [comment]
Closing for now -- please reopen if this resurfaces.
