### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#160]
Let's revisit doing CI -- @galbramc has suggestions and has done this for other software.

**Comment by whoburg** [comment]
@galbramc 's talk on CI:  http://web.mit.edu/galbramc/Public/Developer_Talk_Sandia_2015_Galbraith.pdf

and a paper:
http://web.mit.edu/galbramc/Public/Developer_SciTech_2015_Galbraith.pdf

in the midst of setting up Jenkins to run on ACDL machine...

**Comment by bqpd** [comment]
Is the idea here that we should have some slow-to-run model verification
tests in addition to our quick units tests? (i.e., would we be testing
different tests on the Jenkins server?)

Or would we just be running the unit tests and replacing our habit of
checking that they work before pushing?

**Comment by galbramc** [comment]
The ides is that you can have slow running tests now if you need to. It's
an option. We have tests that take order hours to run for our project, and
there is nothing we can do to make them faster. So we break things up into
multiple stages out of necessity. I would prefer if all our tests were
fast, but it's not an option for us.

With jenkins you no longer have to run the tests before you push. Jenkins
will do it for you automatically. Instead you can focus on running just the
tests associated with code you are actively working on at your workstation,
and let jenkins handle running all the other tests.

If you adopt the pre-merge strategy, then none of your code will get shared
with anyone else unless the test pass.

Thanks,
Marshall

**Comment by whoburg** [comment]
The latter, for now -- run tests automatically. With standardized branch usage, we could also enable automated merging, e.g. of a new "develop" branch to master, when tests pass.

Related issue: https://github.com/convexopt/gpkit/issues/70

**Comment by whoburg** [comment]
From @galbramc:

"""
Need to write a python script or add another function to your test file that will dump a JUnit xml report of the test results. This is how jenkins will know if there is an error in any of the tests.

I did a quick google and there are a number of options to make this happen.
"""

**Comment by whoburg** [comment]
@galbramc is kindly helping us out with getting Jenkins set up to run for us on an internal ACDL machine.

Anyone have confers about this approach / strongly feel we should consider a different route? If not, we'll proceed.

**Comment by bqpd** [comment]
This sounds great!

**Comment by galbramc** [comment]
@bqpd would you be willing to work with me to get gpkit ready for working with jenkins? I don't think there is much work needed on your end. We just need to get the unittests to dump out the results to an xml file.

Also, I would encourage you to consider adding a PyLint test, or something comparable. This is a static analysis tool that will also enforce any coding standard that you feel like adopting. You don't have to add it, but I think you will like it once you do.

**Comment by bqpd** [comment]
Sure thing! Does [this python package](https://pypi.python.org/pypi/XmlTestRunner) look like it could produce the shape of XML we want?

How would you reccomend going about adding a PyLint test?

**Comment by galbramc** [comment]
Yes that should do the trick. Anything that can dump out a JUnit xml file.

For pylint, I would run the command

pylint --generate-rcfile > pylint.cfg

to generate a configuration file. You can put this file anywhere you feel appropriate in the repo. You can then run

pylint --rcfile=pylint.cfg $(find . -name "*.py" -print) gpkit/

to run pylint on all your files, or you can check one file at a time. You will likely not agree with all the complaints from PyLint, so you should modify the cfg file and fix code until you are content.

Once you are happy with the configuration, then change output-format=text to output-format=parseable in the cfg file to generate an xml file for jenkins.

I would start with getting xml output from the unit tests, and then work on PyLint as it will likely take a bit longer.

**Comment by galbramc** [comment]
@bqpd Any luck with generating the xml files? I am willing to help if you would like.

**Comment by galbramc** [comment]
@bqpd @whoburg I needed to look into the xml dump of unit tests for other reasons. In the processes I came up with the following potential solution to getting xml dumps

    def run(xmloutput = False):

        suite = unittest.TestSuite()
        loader = unittest.TestLoader()

        for t in tests:
            suite.addTests(loader.loadTestsFromTestCase(t))

        if xmloutput:
            import xmlrunner
            xmlrunner.XMLTestRunner(output='test-reports').run(suite)
        else:
            unittest.TextTestRunner(verbosity=2).run(suite)

        print "\n######################################################################"
        print "Running with units disabled:"
        gpkit.disableUnits()

        if xmloutput:
            xmlrunner.XMLTestRunner(output='test-reports-nounits').run(suite)
        else:
            unittest.TextTestRunner(verbosity=1).run(suite)

XML reports could then be generated with

python -c "import gpkit.tests; gpkit.tests.run(xmloutput=True)"

Thoughts?

**Comment by galbramc** [comment]
I noticed that I need to run "python setup build" in order for all the unit test to pass. Initially I didn't have ctypesgen installed, so it was not using mosek. I got ctypesgen installed, but I get this message

##
#   To link the mosek libraries we'll create a system-wide conf file
#     Calling 'sudo bash -c 'echo "/home1/jenkins/mosek/7/tools/platform/linux64x86/bin" > /etc/ld.so.conf.d/mosek.conf' '
##

The jenkins user name on reynolds does not have sudo permissions for good reason.  Is there any way to avoid a sudo command in the build?

**Comment by bqpd** [comment]
Status: Jenkins build works on linux, fails when loading MOSEK libs on Mac.

**Comment by whoburg** [comment]
We have prototype working CI thanks to @galbramc.

Remaining issue with Windows CI captured by issue #223.

Pylint issues captured in #216.

Close this?

**Comment by galbramc** [comment]
Sounds good to me.
