### ISSUE TITLE
confusion about how sweeps work on VectorVariable

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#162]
I have some confusion about how sweeps work on `VectorVariable`'s. Goal of this ticket is to document and unit test the expected behavior.

Here's a modified version of `t_GPSubs.test_VectorSweep` from `tests/t_sub.py`:

```python
x = Variable("x")
y = VectorVariable(2, "y")
gp = GP(x, [x >= y.prod()])
gp.sub(y, ('sweep', [[2, 3, 5], [5, 7, 9]]))
a = gp.solve()["cost"]
# a is approx [10, 14, 18, 15, 21, 27, 25, 35, 45]
```

Evidently, the list passed to `gp.sub` for a VectorVariable sweep should have length equal to the length of the vector variable. This makes sense.

One could also envision wanting to sweep the vector across a range of values for the entire vector. Example: we might want to sweep `y` across the values `[[2, 3], [5, 7], [9, 11], [13, 15]]`. Do we support this? It's certainly fine for now if not -- just wondering.

Somewhat unexpectedly, the following code does not raise an exception:

```python
x = Variable("x")
y = VectorVariable(2, "y")
gp = GP(x, [x >= y.prod()])
gp.sub(y, ('sweep', [[2, 3], [5, 7], [9, 11], [13, 15]]))
a = gp.solve()["cost"]
# a is approx [10, 14, 15, 21]
```

Perhaps it should?

Finally, I propose changing the sweep in `t_GPSubs.test_VectorSweep` to something like `gp.sub(y, ('sweep', [[2, 3], [5, 7, 9]]))`, in order to remove any ambiguity created by the current sweep being 2x2.

**Comment by bqpd** [comment]
Sounds good!

We do not currently support sweeping across a list of vector values [[2,
3], [5, 7], [9, 11], [13, 15]]. It breaks the central assumption of the
current sweep code, which is that an n-dimensional array of the various
sweeps can be formed. Easiest solution is to make that an n-dimensional
array of sweep indices, at slight time / memory cost.

Yes, that should raise an error! Just pushed some changes that should cause
that, and your last change.

**Comment by whoburg** [comment]
Added tiny unit test for error raising in 961beb498718315c07b751c50094dc3a19623a41
