### ISSUE TITLE
getting fixed variable values

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#174]
Dumb question: say I have a fixed variable:

```python
from gpkit import Variable
rho = Variable('\\rho', value=1.2)
```
How do I now get the value of rho?

**Comment by bqpd** [comment]
Heh, good question. Right now: `rho.sub(rho)`

But that seems inelegant. What should it be? `rho.subbed`? `rho.value`?

**Comment by bqpd** [comment]
Ack, rho.sub(rho) doesn't work, never mind.

**Comment by bqpd** [comment]
If you pull, rho.value will work, returning a Posynomial for any Posynomial
with all valued vars substituted.

**Comment by whoburg** [comment]
Added a unit test in b47f2cc2f65e263d76904656646957442475e5d0.

The only thing not working as expected is `x.value` when `x` is an unvalued `Variable`. I claim the commented out line in the test below should work:

```python
    def test_value(self):
        a = Variable('a')
        b = Variable('b', value=4)
        c = a**2 + b
        self.assertEqual(b.value, 4)
        self.assertEqual(float(b.value), 4.0)
        self.assertEqual(c.value, a**2 + 4)
        # next test should work, but currently fails
        # self.assertEqual(a.value, a)
```
but current output is
```python
======================================================================
ERROR: test_value (t_vars.t_Variable)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<>/gpkit/gpkit/tests/t_vars.py", line 77, in test_value
    self.assertEqual(a.value, a)
  File "gpkit/nomials.py", line 258, in value
    for vk in self.varkeys.values()
  File "gpkit/nomials.py", line 268, in sub
    substitutions, val)
  File "gpkit/substitution.py", line 99, in substitution
    raise KeyError("could not find anything to substitute in %s" % substitutions)
KeyError: 'could not find anything to substitute in {}'

----------------------------------------------------------------------
Ran 52 tests in 0.971s

FAILED (errors=1)
```

**Comment by whoburg** [comment]
Design discussion: it's clear that `Posynomial.value` should return a `Posynomial` (in case some of the involved variables don't have substitution values).

But, should `Variable.value` act differently? Otherwise, one has to call `float(x.value)` to actually get a float out...

**Comment by bqpd** [comment]
If the result is a number or Quantity it should be returned directly, I think! That won't prevent any posynomial operations, so no reasong to keep it locked up.

**Comment by whoburg** [comment]
This looks great!
