### ISSUE TITLE
Signomial Programming -- Simple Example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#176]
I'm on this -- planning to do a cannon simulation with drag.

**Comment by whoburg** [comment]
Cannon sim is surprisingly hard (but super interesting) -- might switch to an easier initial example and then revisit the cannon.

**Comment by bqpd** [comment]
It'd be great to see the cannon-in-progress! (should we have a better way to share models-in-progress, or just use the dropbox?)

**Comment by bqpd** [comment]
(what's the status on this?)

**Comment by pgkirsch** [comment]
Possible example: wing sweep

**Comment by bqpd** [comment]
I'm going to close this for now; I think it's superseded by the desire for models in general for gpkit-model, as some of those will be Signomial!
