### ISSUE TITLE
Minus signs in objective functions

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#177]
I want this to work:

```python
import gpkit
import gpkit.interactive
gpkit.interactive.init_printing()
%matplotlib inline
import matplotlib.pyplot as plt

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^2", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,10), "-", "Pareto Sweep Variable")

eqns = [L*W==10*gpkit.units.m**2]

Obj = a*(2*L+2*W) + (a-1)*(12 * W**-1 * L**-3)

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()

```

but right now it doesn't know how to handle the `a-1`.  I can get around it, but it would be nice to have the functionality.

**Comment by bqpd** [comment]
In the FotW I implicitly noted that we don't support minus signs in the
objective functions: it's not clear how one would make a monomial
approximation when it's not a constraint.

We could automatically do what you've probably done, which is make a
constraint relating the signomial in question to a monomial, and then
min/max that extra monomial, but I'm a bit leary of automatically adding
constraints...

**Comment by cjk12** [comment]
Is there any way we could make objective functions their own class?  There are also some unit issues that I don't like having to deal with.  Basically, its much harder to write useful MOO problems right now in GPkit than I had anticipated before attempting to write one...

**Comment by bqpd** [comment]
(MOO = Multi Objective Optimization?)

**Comment by cjk12** [comment]
Yes.

**Comment by cjk12** [comment]
Yea, essentially that's what it boils down to.

So, I have realized in the past two days that sweeps are not the same as classical MOO.  What you have just described is.  It essentially allows me to tweak my objective function using some swept variable and then I can plot how my two objectives change as I sweep along this variable (this is the classical definition of a Pareto Frontier)

**Comment by bqpd** [comment]
Hmm, do you have an example of a program you'd like to run, so I can try formatting it as a sweep?

**Comment by cjk12** [comment]
Not at the moment.  That's what I'll be working on today.  I'm currently doing it just for a simple rectangle (what I posted above), but later this week I'm going to put together one using aircraft design.  We are trying to make an example of how GP can produce objective functions for higher fidelity optimization runs.

**Comment by bqpd** [comment]
Okay, here's how to get what you posted above to work:

```python
%matplotlib inline
import matplotlib.pyplot as plt

import gpkit
gpkit.enable_signomials = True

import gpkit.interactive
gpkit.interactive.init_printing()

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^2", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,10), "-", "Pareto Sweep Variable")

eqns = [L*W==10*gpkit.units.m**2,
        Obj >= a*(2*L+2*W) + (a-1)*(12 * W**-1 * L**-3)]

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()
```

**Comment by cjk12** [comment]
Yea, ok.  So that fixes my minus sign issue. Cool.

It's not liking when a=0 now though.  Here is what I'm working with at the moment:

```python
import numpy as np
import gpkit
import gpkit.interactive
gpkit.interactive.init_printing()
%matplotlib inline
import matplotlib.pyplot as plt

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^4", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,11), "-", "Pareto Sweep Variable 1")
b = gpkit.Variable("b", 1-np.linspace(0,1,11), "m^5", "Pareto Sweep Variable 2")

eqns = [L*W==10*gpkit.units.m**2,
        L>=1*gpkit.units.m,
        W>=1*gpkit.units.m]

Obj = a*(2*L+2*W)*gpkit.units.m**-5 + b*(12 * W**-1 * L**-3)

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()
print "Done"
```

**Comment by bqpd** [comment]
Right, because `a` and `b` are no longer linked, so there's a case where both a and b are 0.

**Comment by cjk12** [comment]
Ok, so I think I fixed that, but my kernel is still dying...

```python
import numpy as np
import gpkit
import gpkit.interactive
gpkit.interactive.init_printing()
%matplotlib inline
import matplotlib.pyplot as plt
gpkit.enable_signomials = True

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "m", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,11), "-", "Pareto Sweep Variable")

eqns = [L*W==10*gpkit.units.m**2,
        L>=1*gpkit.units.m,
        W>=1*gpkit.units.m]

Obj = a*(2*L+2*W) + (a-1)*(12 * W**-1 * L**-3)*gpkit.units.m**5

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()
print "Done"
```

**Comment by bqpd** [comment]
Looking into it, this might be a bug in Signomial programming. (if so, excellent!)

**Comment by cjk12** [comment]
*Sigh*...  Well, apparently that is my function in the group...  Yours does it to in case you are interested:

```python
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

import gpkit
gpkit.enable_signomials = True

import gpkit.interactive
gpkit.interactive.init_printing()

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "m", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,10), "-", "Pareto Sweep Variable")

eqns = [L*W==10*gpkit.units.m**2,
        Obj >= a*(2*L+2*W) + (a-1)*(12 * W**-1 * L**-3)*gpkit.units.m**5]

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()
```

**Comment by bqpd** [comment]
First thing I noticed was that you need to call `gpkit.SP` and `gpkit.localsolve`, but there's another bug further down...

**Comment by cjk12** [comment]
I'm going to add another issue, because the fact that this simple of an MOO problem requires using SP's I think is an issue that warrants further discussion.

**Comment by bqpd** [comment]
You think there's an equivalent GP formulation? Anything with a minus sign has to be SP, but if you can remove that...

**Comment by cjk12** [comment]
I'm not sure, that's why I started the new issue :)  

The reason I think it should be GP is that I'm literally trying to put a constant multiplier in front of a number.  It should totally be GP compatible but for some reason is causing issues...

**Comment by cjk12** [comment]
I mean, this is really all I want, but the units are pitching fits now...

```python
import numpy as np
import gpkit
import gpkit.interactive
gpkit.interactive.init_printing()
%matplotlib inline
import matplotlib.pyplot as plt
gpkit.enable_signomials = True
gpkit.disableUnits()

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "m", "Objective")

# a = gpkit.Variable("a", np.linspace(0,1,11), "-", "Pareto Sweep Variable")

a = np.linspace(0,1,11)

eqns = [L*W==10*gpkit.units.m**2,
        L>=1*gpkit.units.m,
        W>=1*gpkit.units.m]

Obj = a*(2*L+2*W) + (a-1)*(12 * W**-1 * L**-3)

gp = gpkit.GP(Obj, eqns)
sol = gp.solve()
print "Done"
```

**Comment by bqpd** [comment]
The only reason it's causing issues is that sometimes that multipler is negative. Did you by chance mean `1-a` instead?

**Comment by cjk12** [comment]
Oops...  Yea...

**Comment by bqpd** [comment]
Also, the units are pitching fits because, under that formulation, your answer would change based on your units basis. Units are real! :p

**Comment by cjk12** [comment]
But I dont care what they are at the moment, I just want my problem to work :p  This has been my complaint about units all along. Sometimes, I just want it to ignore them and run my code...

**Comment by bqpd** [comment]
It's a pale kind of "working" when changing from imperial to metric changes your result.

**Comment by cjk12** [comment]
But I don't care what the result is at the moment either, because I have no result to look at.  I just have error messages...

**Comment by cjk12** [comment]
Back on topic, kernel is still dying...

```python
import numpy as np
import gpkit
import gpkit.interactive
gpkit.interactive.init_printing()
%matplotlib inline
import matplotlib.pyplot as plt
gpkit.enable_signomials = True


L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "m", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,11), "-", "Pareto Sweep Variable")

eqns = [L*W==10*gpkit.units.m**2,
        L>=1*gpkit.units.m,
        W>=1*gpkit.units.m,
        ]

Obj = a*(2*L+2*W) + (1-a)*(12 * W**-1 * L**-3)*gpkit.units.m**5

gp = gpkit.SP(Obj, eqns)
sol = gp.localsolve()
print "Done"
```

**Comment by bqpd** [comment]
Ack, doing this kind of manipulation (1-a, that is) during a sweep doesn't work with our current implementation of sweeps, because we assume that no additional simplification steps need to happen after substitution into a GP (which is true if there aren't any zeroes or minus signs).

I don't think this assumption is worth the minor increase in speed, so I think I'll remove it.

**Comment by cjk12** [comment]
Does that mean if I pull my code will run?

**Comment by bqpd** [comment]
Well, this will run:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

import gpkit
gpkit.enable_signomials = True
gpkit.disableUnits()

import gpkit.interactive
gpkit.interactive.init_printing()

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^4", "Objective")

a = gpkit.Variable("a", np.linspace(0.01,0.99,10), "-", "Pareto Sweep Variable")

eqns = [L >= 1, W >= 1,
        L*W == 10,
        Obj >= a*(2*L+2*W) + (1-a)*(12 * W**-1 * L**-3)]

gp = gpkit.SP(Obj, eqns)
gp.localsolve()
```

**Comment by bqpd** [comment]
But the larger problem of working as a GP is better discussed in the other thread.

**Comment by cjk12** [comment]
ok, cool.  Thanks.

**Comment by bqpd** [comment]
The above now runs with
```python
a = gpkit.Variable("a", np.linspace(0, 1, 10), "-", "Pareto Sweep Variable")
```
