### ISSUE TITLE
Multi Objective Optimization in GPkit

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#178]
Related to #177 , it's somewhat difficult to do classical MOO in GPkit, and appears to require the use of SP's.  I think this warrants some discussion, as MOO is somewhat important...

**Comment by bqpd** [comment]
Since you know more about conventional MOO formulation than I do, could you take a look at the aircraft example?

If MOO relies upon the affine `(a-1)` functions that you use in #177, then that will certainly be problematic.

**Comment by cjk12** [comment]
"If MOO relies upon the affine `(a-1)` functions that you use in #177, then that will certainly be problematic."

As we just discovered, that should in fact be `(1-a)`.

Which aircraft design example are we talking about?

**Comment by bqpd** [comment]
I was thinking of [the Fuel one](http://gpkit.readthedocs.org/en/latest/ipynb/Fuel/Fuel.html).

So, if those are `(1-a)`, then we could support them; however, I'm leary of having some things with minus signs work as GPs while others do not.

**Comment by cjk12** [comment]
Yea, ok, that one is weird because one of the trades is stall speed, which valid, is not a traditional objective in MOO.

Additionally, this example basically optimizes multiple aircraft with different constraints, rather than telling me how the aircraft changes as I change my objective.  The second is much more useful for making design decisions.

This is my Thursday/Friday project, but I need to understand how GPkit will work with MOO, hence #177.  I'll get back to you on this.

**Comment by bqpd** [comment]
re: "telling me how the aircraft changes as I change my objective"
Oh, interesting. Good to know

**Comment by cjk12** [comment]
Yea, I mean, physics is basically always going to set my constraints.  How I design an airplane is dependent on how much I want to carry, how far I want it to go, how fast it gets there etc...

**Comment by bqpd** [comment]
Hmm, no longer following you. The fuel example is directly setting the minimum required stall speed, range, etc., and would hence seem to fit your most recent description rather well.

**Comment by cjk12** [comment]
At the high level, I only really care about stall speed if it is preventing me from landing on a short runway.  Normally when I start conceptual design trends, I'm more concerned with which airplane I want do design, not how the airplane will be limited.   Granted, limits on stall speed are important, but I'll generally set that based on the mission parameter for runway length, which is the parameter I care more about at the top level.  We can talk about this more on Thursday.  I don't think I'm illustrating my point terribly clearly....

**Comment by bqpd** [comment]
If I'm tracking, though, then what you're describing is still better thought of as a sweep of the constraint rather than a sweep of the objective?

**Comment by cjk12** [comment]
It's a different angle to attack the problem.  If I'm designing the new 737, the first thing I'm going to do is look at performance parameters: range, payload and cruise speed, and then attack how to maximize all these things.  I need the ability to study these as objectives and see what that does to my design.  You could try constraining each of these things, but then what is you objective function, fuel?  If all my airplanes are designed for minimum fuel, that gives me no intelligent point of common comparison.  What we want to do is say for these fixed constraints, when I sacrifice range, how much extra payload does that give me?  Hence, a MOO problem.  Are you on campus by chance?  I feel like we are totally spamming the github at the moment...

**Comment by bqpd** [comment]
In your example, couldn't you use payload as your common objective, and sweep over range and cruise speed?

**Comment by cjk12** [comment]
I'll have to give that some thought.  My first thought is no because I want to be able to sweep out a pareto frontier, but I might just not quite get how you are planning to do that at the moment...

**Comment by bqpd** [comment]
If you use payload as your common objective and sweep over range and cruise speed, you'll get what I call a "design frontier", which is just a Pareto frontier that allows (instead of collapsing) flat spots in range and cruise speed.

The alternative, of linearly interpolating between each objective, makes me shudder a bit from a units standpoint. :p

**Comment by cjk12** [comment]
I'm not sure I completely get what you are calling a design frontier...

Linear interpolation like this is widely accepted practice for sweeping MOO problems.  Granted, you have to assume continuity between solutions, but you can decrease step size to where this isnt a problem.  Plus for our convex/nearly convex problems, this really isnt that far of a stretch to assume continuity.

**Comment by bqpd** [comment]
I agree that the method gets results, but I think it's wasteful (i.e. requires more solves) and has less physical meaning than a sweep-based approach. Looking forward to talking about it in person, though!

For the meantime, there's the question of "should we support `(1-a)` in GPs?". 

Doing this kind of manipulation during a sweep doesn't work with our current implementation of sweeps, because we assume that no additional simplification steps need to happen after substitution into a GP (which is true if there aren't any zeroes or minus signs).

We could remove this assumption. Alternately, we could specify a new sweep class:

```python
a_ = gpkit.LinkedSweep(a, lambda a_i: 1-a_i)
```
Where we create a gpkit Variable-alike that says what sweep variables it links to and the way to determine its value as a function of those sweep variables.

This would also give us "cases" (re: a very old ticket by @whoburg) for free.

**Comment by cjk12** [comment]
I would suggest the creation of an `Objective` class that has different rules than those currently in `Monomial`, `Posynomial`, `Variable` etc...  I think this also helps out with our approach of emphasizing objective functions as important.

**Comment by bqpd** [comment]
I don't think that creating an `Objective` class won't fix the problem with (`1-a`), or the issue of dealing with units when  doing an interpolation.

The only thing that I think it would make easier is the creation of dummy constraints for signomial programs when the objective function is a signomial.

**Comment by cjk12** [comment]
I disagree on the point that objective functions are made of the same stuff as everything else. I mean, they are, but when I perform an optimization, the objective is something unique I keep in my head.  

And couldn't we define the `-` operator in the `Objective` class?  I guess I'm not entirely understanding what you are saying...

**Comment by bqpd** [comment]
Naw, `-` is defined in the monomial / posynomial / variable classes, so to use minus with only those things in the objective you'd have to define the variables that would be going in your objective to be somehow special.

**Comment by cjk12** [comment]
Ah, I see the problem...

**Comment by bqpd** [comment]
@cjk12: which of the two solutions above do you prefer? The latter is more general (especially to the n-dimensional case), but might be a little more confusing to read?

(@whoburg, @pgkirsch : would love your thoughts on the two proposed solutions above as well!)

**Comment by cjk12** [comment]
So I don't completely understand the background for them, but either one seems fine.

The one thing I do want, is both `a` and `a-1` should be able to be zero.  I'm looking at one of my Pareto curves here, and because the spacing is logarithmic, I'm missing like half the Pareto Frontier because the best I can to is 0.01...  As I mentioned in #177, I'm simply multiplying by a constant, or else ignoring part of my objective function (when `a=0,1`), so it should be GP compatible.

**Comment by bqpd** [comment]
Ah, good point re: zeroing. That's a simple fix, I'll do that right now.

**Comment by cjk12** [comment]
Cool, let me know when it's in so I can pull.

**Comment by bqpd** [comment]
It's in. Note that you'll still need to enable Signomials if you want to do subtraction, and that this still won't allow you to do interpolation as a GP; in my example in #179, it just allows you to sweep from a = 0 to a = 1.

**Comment by cjk12** [comment]
This is great.  Thanks.

**Comment by bqpd** [comment]
This is now possible as a GP. Also, we have sensitivies, and linked sweeps. Documentation incoming, for now here's the example: 

```python
import numpy as np

import gpkit
gpkit.disableUnits()

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")

eqns = [L >= 1, W >= 1,
        L*W == 10]

obj = gpkit.MOO(L+W, W**-1 * L**-3, sub={L:1, W: 1}, sweep=[0]+np.logspace(-6, 0, 10).tolist())

gp = gpkit.GP(obj, eqns)
sol = gp.solve()
sol["sensitivities"]["variables"]
```
