### ISSUE TITLE
Sensitivities

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#179]
So, I'm getting out all these numbers in array for sensitivities.  What do these actually mean for my design problem?  IE, how do I know what number corresponds to what variable/monomial/posynomial (this part also doesn't make much sense..) and then also, what is this the slope with respect to?  The objective function?  If we have this documented already, a simple link to that would be great.

**Comment by bqpd** [comment]
For each item `x`, the sensitivity is `d log(x)/d(Obj)`.

The easiest way to use this is to use `sol.senssubinto(v)`, where v is the variable you want to know the sensitivity of.

If you want to access the values directly: 

`gp.solution["sensitivities"]` has three fields: `variables`, `monomials`, and `posynomials`.

`gp.solution["sensitivities"]["variables"]` is a dictionary where the keys are variables and the values are the sensitivities.

**Comment by cjk12** [comment]
Cool, thanks.

**Comment by cjk12** [comment]
For `sol.senssubinto(v)`, is `v` a string?

**Comment by bqpd** [comment]
No, a Variable.

**Comment by cjk12** [comment]
So this doesn't work either:

`sol.senssubinto(sol['variables']['W'])`

Can you give an example?  the Read the Docs for this is also quite sparse...

**Comment by bqpd** [comment]
try `sol.senssubinto(W)`

**Comment by cjk12** [comment]
```
AttributeError: 'numpy.ndarray' object has no attribute 'sub'
```

**Comment by bqpd** [comment]
`sol['variables']['W']` does not return a Variable. A Variable is that which is returned by `gpkit.Variable`

**Comment by bqpd** [comment]
This might be easier if you pasted your code.

**Comment by cjk12** [comment]
Yea, that error was for:

```python
sol.senssubinto(W)
```

**Comment by cjk12** [comment]
wait, I redefined W at one point...  Let me fix that and the problem might go away...

**Comment by cjk12** [comment]
It didnt go away, so here it is:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

import gpkit
gpkit.enable_signomials = True
gpkit.disableUnits()

import gpkit.interactive
# gpkit.interactive.init_printing()

N=10

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^4", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,N), "-", "Pareto Sweep Variable")

eqns = [L <=10,
        W <=10,
        L*W == 10,
        Obj >= a*(2*L+2*W) + (1-a)*(12 * W**-1 * L**-3)]

gp = gpkit.SP(Obj, eqns)
sol=gp.localsolve()
sol.senssubinto(W)
```

**Comment by bqpd** [comment]
Oh, it's for a signomial program. Those currently don't support sensitivities, I'm afraid.

**Comment by bqpd** [comment]
Working on it as part of a larger Model/GP/SP refactoring.

**Comment by cjk12** [comment]
Aww...  Well, looks like I'm stuck for the moment...

**Comment by bqpd** [comment]
I can do a quick workaround.

**Comment by cjk12** [comment]
Nah, do it right.  I have some other stuff I can work on.  Thanks though.

**Comment by bqpd** [comment]
You want to get the sensitivity to...`a`?

**Comment by cjk12** [comment]
I ideally want everything.  I'm not totally sure what I want yet.

**Comment by bqpd** [comment]
Errr, actually I can tell you what the sensitivity to `W` is. It's `0`, since `W` is a free_variable.

**Comment by bqpd** [comment]
Only constants (`a` in this problem) have non-zero sensitivities

**Comment by cjk12** [comment]
Ok, so I guess I want the sensitivity to the `L<=10` constraint actually.  Note I flipped variables

**Comment by bqpd** [comment]
We can do that pretty easily. Normally you'd declare `L <= L_max` and then find the sensitivity of `L_max`, but here we can do it from the monomial sensitivities.

**Comment by cjk12** [comment]
Ok, I can do L_max.  That's fine.  Anyway, not important until after it's been implemented for signomials.

**Comment by bqpd** [comment]
Here it is:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

import gpkit
gpkit.enable_signomials = True
gpkit.disableUnits()

import gpkit.interactive
gpkit.interactive.init_printing()

N=10

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^4", "Objective")

a = gpkit.Variable("a", np.linspace(0,1,N), "-", "Pareto Sweep Variable")

eqns = [L <= 10,
        W <= 10,
        L*W == 10,
        Obj >= a*(2*L+2*W) + (1-a)*(12 * W**-1 * L**-3)]

gp = gpkit.SP(Obj, eqns)
sol=gp.localsolve()

sensLmax = [nus[1] for nus in sol["sensitivities"]["monomials"]]
sensWmax = [nus[2] for nus in sol["sensitivities"]["monomials"]]

plt.semilogy(sol(a), sensLmax)
plt.semilogy(sol(a), sensWmax)
```

It looks to be rather insensitive except at a=0. The value at a=0  is 2, as one would expect given that obj reduces to (12 * W**-1 * L**-3) = 12 * L**-2.

**Comment by bqpd** [comment]
Implementing signomial sensitivity might not happen for a while, so for this case of caring about maxes I'd use the above method for now...

**Comment by cjk12** [comment]
Yea, ok, that's what I'd expect here.  I'm going to need it soonish to do some early trade study work, but not in a huge rush.  Gotta figure out exactly what I want to do first.

**Comment by whoburg** [comment]
Re: what exactly do the sensitivities represent, I'd strongly suggest reading section 3.3 of http://stanford.edu/~boyd/papers/gp_tutorial.html, and sections 3.2-3.3 of http://web.mit.edu/~whoburg/www/papers/hoburg_phd_thesis.pdf.
