### ISSUE TITLE
Water Tank example needs short description

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#182]
Who made the Water Tank example here: http://gpkit.readthedocs.org/en/latest/examples.html?

We need to add a short description of the problem being solved.

Note the new semi-automated way of generating output files for our examples, implemented by 51f274291f30270832fe7feedd7f8c0a3b1119a9. Basically, if you change an example file, you can automatically generate all output for all example files by navigating to gpkit/docs/ and typing `make examples`. Then push the changed *_output.txt files to the repo.

**Comment by cjk12** [comment]
This is me.  What's the priority here?

**Comment by whoburg** [comment]
Not high priority, but also not looking for anything too complicated -- just a sentence or two describing what the problem is and what's being optimized.

**Comment by cjk12** [comment]
Yea, that's easy, but I have to remember how to change the documentation again, so that will be the delay.  I'll get to it sometime this week.

**Comment by whoburg** [comment]
In this case all you have to do is edit docs/source/examples.rst and push changes to the gpkit repo. The documentation will update automatically (you can also force the update after pushing by clicking on "Build" here:https://readthedocs.org/projects/gpkit/).

**Comment by cjk12** [comment]
Updated.  Further edits can be added to this thread and I will update.
