### ISSUE TITLE
Fuel example missing aircraft cadtoon

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#186]
High priority:  I just made some minor updates to `docs/source/ipynb/Fuel/Fuel.ipynb` in 4f2d074404dce4067af71a1eb38d5e7922246285, and noticed that the cadtoons are not showing up.

Would be great if this could be fixed tonight for a talk tomorrow.

**Comment by bqpd** [comment]
It's a Ractive.js bug, all of the interactive notebooks are broken (even
the code from v0.1.0
<http://nbviewer.ipython.org/github/convexopt/gpkit/blob/v0.1.0/docs/source/ipynb/Fuel/Fuel.ipynb>).
Tracking it down...

**Comment by bqpd** [comment]
Fixed after reverting to old Ractive version.

**Comment by whoburg** [comment]
perfect, thanks!
