### ISSUE TITLE
Sensitivity Help

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#187]
So, I'm currently working with this:

```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math as math
import gpkit
import gpkit.interactive
# ===================================
N=20
indx = 10

A_min_val = 10
P_vals = np.linspace(12.6,13.5,N)
change_perc = .01
# ===================================
L_max = gpkit.Variable("L_max", 10, "m", "Length")

L = gpkit.Variable("L", "m", "Length")
W = gpkit.Variable("W", "m", "Width")
Obj = gpkit.Variable("Obj", "1/m^4", "Objective")
A = gpkit.Variable("A", "m^2", "Area")
P = gpkit.Variable("P",P_vals,"m","Perimeter")
I = gpkit.Variable("I","m^4","Perimeter")
# ========================================================================
A_min = gpkit.Variable("A_min", A_min_val, "m^2", "Area")
eqns = [L <= L_max,
        L*W >= A_min,
        P >= 2*L+2*W,
        I == 1./12*W*L**3,
        Obj == 1/I,
        ]

gp = gpkit.GP(Obj, eqns)
sol_A10=gp.solve(skipfailures=True, printing=False)
# =============================================================================
print sol_A10.senssubinto(A_min)[indx]
```

Which prints:
```python
1.59635734012
```

So, my understanding of this is that for an increase in `A_min` of 1%, `1/I` (my objective) will `Increase` by about 1.6%.  Is that a correct understanding?  If it is, this result is opposite of what should be occurring.  Increasing `A_min` should also drive up `I` (or drive down `1/I`).

**Comment by bqpd** [comment]
To work as a constraint, `L*W` must be being driven down into `A_min` by
the objective, which means that an increase in `A_min` will make your
objective worse (larger) if it does anything.

This is confirmed by changing the value of A_min.

**Comment by cjk12** [comment]
Ok, its because I'm doing a strange bound...  Hmm...  I need to give this some thought...  Thanks @bqpd

**Comment by bqpd** [comment]
Remember, you can always check the sensitivity by doing a couple nearby
solves!

**Comment by cjk12** [comment]
Yea, the reason I posted this is because I'm struggling with a couple larger issues related to my nearby solves...  This certainly helps though.
