### ISSUE TITLE
(Temporarily) appending zero to a PosyArray

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#189]
Best practices question -- I want to add two PosyArray's whose lengths differ by one. For the last index (where only one of the PosyArrays has a value), I want the other PosyArray to be treated as zero.

The following code solves my problem:

```python
import numpy as np
from gpkit import VectorVariable
x = VectorVariable(4, 'x')
y = VectorVariable(5, 'y')
np.hstack((x, 0)) + y
```
output:
```
gpkit.PosyArray([x_0 + y_0, x_1 + y_1, x_2 + y_2, x_3 + y_3, y_4])
```

My question: is the `hstack` method above the preferred/best way to do this? (I'm not looking for any new gpkit functionality, just instructions for using existing gpkit and numpy tools)

**Comment by bqpd** [comment]
Yeah, hstack seems like the right way to do it. :)
