### ISSUE TITLE
refactor PosyTuple to GPTuple

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#190]
will contain everything needed to create a GP

BTW, this currently works
```python
# assume ptup is a PosyTuple
from gpkit import Posynomial
p = Posynomial(*ptup)
```
should discuss how this will work for `GPTuple` -- probably modify `GP.__init__` to take in a PosyTuple

also update `GP.load`?

**Comment by bqpd** [comment]
Old, but falls under the heading of "NomialData". Posytuple is going away, and GP refactor makes Model construction very different.

**Comment by whoburg** [comment]
The intent of this ticket was completed in the GP/Model refactor.
