### ISSUE TITLE
Install script is not always run by pip?

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#196]
Seen on @jpmjanelle's machine.

**Comment by bqpd** [comment]
We should confirm that this is still an issue with the new build script on @jpmjanelle's machine.

**Comment by jpmjanelle** [comment]
should i try to reinstall gpkit with the pip instructions?

**Comment by bqpd** [comment]
There's a couple other changes that'll need to be made before reinstalling,
so I can do it next group meeting.

**Comment by whoburg** [comment]
Status of this?

**Comment by bqpd** [comment]
Could not reproduce, can probably be closed.

We added a "blank settings file" warning to import during Jenkins setup, so if this occurs again we'll get a useful error message.
