### ISSUE TITLE
docs/source/ipynb/simpleaircraft is broken

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#197]
(due to API changes -- `monify_up` and `init_printing` no longer exist, etc)

Edit: now due to errors raised in the ractorpy block.

**Comment by whoburg** [comment]
I'm getting an `AttributeError: 'numpy.float64' object has no attribute 'units'` in the ractorpy block.

**Comment by bqpd** [comment]
"Fixed" by realizing it was actually a deeper copy issue: #293
