### ISSUE TITLE
make QPROP example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#202]

**Comment by bqpd** [comment]
(what's the status on this?)

**Comment by whoburg** [comment]
Status is that I got distracted by other things partway through making this, but I will get back on it.

It will be helpful to have signomial equality constraints working, in order to get this working...

**Comment by bqpd** [comment]
Haha, excellent!

**Comment by bqpd** [comment]
Moved to https://github.com/aeroa/gpkit-models/issues/3
