### ISSUE TITLE
Installing cvxopt on windows

### ISSUE THREAD

**Issue by galbramc** [convexopt/gpkit#209]
I'm stuck trying to compile cvxopt on windows. I've installed Anaconda, MingW, compiled blas and lapack, but I get a link error with a bunch of undefined references to python functions when I try to build cvxopt. Does anyone have a solution to this?

**Comment by bqpd** [comment]
I gave up on installing cvxopt on my own windows machine...it's a giant
mess.

It sounds like the compiler might need the python header file, etc., from
$PYTHON\include?

**Comment by galbramc** [comment]
No this is a library issue, but if you gave up then I am giving up. No cvxopt testing on windows.
