### ISSUE TITLE
Copy release notes to docs

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#210]
Reminder to move the release notes draft here: https://github.com/convexopt/gpkit/releases to the documentation. Also add relevant links.

**Comment by bqpd** [comment]
Added release notes w/o links, so I think this might be ready to close; I'll leave @whoburg as the arbiter of that.

**Comment by whoburg** [comment]
Ok - would be nice to include links to the commits/pull requests/etc that enable each feature, but let's consider that the plan going forward and not needed for this release.

Instead of closing this I changed it to 0.3.0, so we will be sure to do it again there.

**Comment by whoburg** [comment]
Err wait, the links were intended to be within the documentation. That's a better plan anyway. We'll do that going forward.

**Comment by bqpd** [comment]
Superseded by #332.
