### ISSUE TITLE
improve partitioning of variables (into free variables, constants, etc)

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#212]
Results table used to separate free variables from constants, but I think I accidentally killed that behavior with https://github.com/convexopt/gpkit/pull/191. Should separate them again -- that was nice.

**Comment by whoburg** [comment]
Good example of the difference is here: 363b8ec0b04ba74673e817fbbe753a91c0306938

**Comment by bqpd** [comment]
Oops, no, I killed it accidentally during the Signomial programming
process; GPSolutionArray no longer distinguishes!

We were talking about giving GPSolutionArray some additional information
about the program, and variable-type could be a good candidate.

**Comment by whoburg** [comment]
Should we think about putting this info in the `VarKey`? Or is that dumb?

**Comment by bqpd** [comment]
Hmmmm. I'd store it in the solution array and keep the VarKeys as the user created them.

**Comment by whoburg** [comment]
Just to make sure, what I meant is, if I call 

`x = Variable('x', 3, 'm')`

and then look at the resulting `VarKey`, there's no way I can see to tell that this `VarKey` corresponds to a constant. Should there be? I feel like maybe we've already visited this question though. Sorry if I'm derailing.

**Comment by bqpd** [comment]
Sure you can tell; `x.value != x`, therefore it's a constant.

alternate test: `"value" in x.varkeys.values()[0].descr`

**Comment by whoburg** [comment]
This broke `docs/source/examples/simple_box.py`:

```python
examples whoburg$ python simple_box.py
Traceback (most recent call last):
  File "simple_box.py", line 35, in <module>
    print sol.table()
  File ".../anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/geometric_program.py", line 125, in table
    strs += [results_table({k: v[0] for (k, v) in self["variables"].items()
  File ".../anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/geometric_program.py", line 126, in <dictcomp>
    if k in self.gp.substitutions},
IndexError: too many indices for array
```

**Comment by bqpd** [comment]
Yeah, it wasn't the greatest way to do this. It's fixed in my gp-refactor branch, so I'll focus on getting that working...

**Comment by whoburg** [comment]
It seems to me that perhaps the partitioning of variables (into free variables, constants, etc) should be either a `@property` or an attribute at the `GPSolutionArray` level -- right now it happens inside the `table()` method, but I can imagine other places we might want this partitioning...

**Comment by bqpd** [comment]
Yup. I'm putting it in results parsing in the refactor, to minimize pointers.

**Comment by whoburg** [comment]
Ok, `simple_box.py` appears to work again. Sounds like the remaining issues are planned to be fixed in the GP/Model refactor -- should we move this to 0.3.0?

**Comment by whoburg** [comment]
Also, title seems off

**Comment by bqpd** [comment]
Variables are automatically partitioned in the Model refactor, and it carries through to the SolutionArray.
