### ISSUE TITLE
result table printing -- should print units of cost

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#214]
* [ ] Costs have units too.

* [ ] Determining them might also make a nice opportunity to confirm that the solver's returned cost really does equal the value of the solution substituted into the objective, and raise an exception if not.

**Comment by bqpd** [comment]
Yes indeed!

**Comment by whoburg** [comment]
In order to implement this, along with other solution-checking features, I suspect we'll need a link from `GPSolutionArray`s back to the `GP` they came from. Any thoughts or opinions on how to architect that?

**Comment by bqpd** [comment]
I don't think that the second bullet point there is correct; we'll probably determine the cost's units just by querying the objective.

Have the solutionarray contain a pointer to the GP seems reasonable? `sol.gp` etc.
