### ISSUE TITLE
Unit tests failing (but only in the root of my local git repo)

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#220]
I just pulled and I'm getting 23 errors and 1 failure.

**Comment by pgkirsch** [comment]
Strangely enough, this only happens when I am in my local gpkit repository. If I run unit tests from another directory, they all pass.

**Comment by bqpd** [comment]
Hmm. I'll take a look on Thursday,

**Comment by whoburg** [comment]
Unit tests are all passing for me -- @pgkirsch could you please paste all or some of the output?

**Comment by pgkirsch** [comment]
Issue was fixed by re-running the build script
