### ISSUE TITLE
build script tries to delete non-empty directory

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#223]
from @galbramc and CI testing:

Now I think we are getting a legit (though windows specific) error when gpkit tries to delete a temporary folder that is not empty. Apprently windows shuns upon deleting non-empty folders...

**Comment by whoburg** [comment]
Still getting build failures due to this

```
Stacktrace

Traceback (most recent call last):
  File "gpkit\tests\t_sub.py", line 69, in test_VectorSweep
    a = gp.solve(printing=False)["cost"]
  File "gpkit\geometric_program.py", line 335, in solve
    return self._solve(*args, **kwargs)
  File "gpkit\geometric_program.py", line 380, in _solve
    solution = self._solve_sweep(printing, skipfailures, allownonoptimal)
  File "gpkit\geometric_program.py", line 451, in _solve_sweep
    for sol in mapfn(run_solver_i, range(N_passes)):
  File "gpkit\geometric_program.py", line 444, in run_solver_i
    return self._run_solver(allownonoptimal)
  File "gpkit\geometric_program.py", line 466, in _run_solver
    result = self.solverfn(c=cs, A=A, p_idxs=p_idxs, k=k)
  File "gpkit\_mosek\cli_expopt.py", line 99, in imize
    os.removedirs("gpkit_tmp")
  File "C:\Anaconda\lib\os.py", line 170, in removedirs
    rmdir(name)
WindowsError: [Error 145] The directory is not empty: 'gpkit_tmp'
```

**Comment by bqpd** [comment]
I think this worked on my windows 8 machine, but we can manually empty
directories as DOS prefers.

**Comment by galbramc** [comment]
The tasting is done on a Windows 7 virtual machine. I would imagine that deleting all the files in the directory first should do the trick.

**Comment by bqpd** [comment]
[stackoverflow reference](http://stackoverflow.com/questions/2656322/python-shutil-rmtree-fails-on-windows-with-access-is-denied)

We're using `rmtree`, which _should_ work if the directory is not read-only. But it doesn't seem to be. 

One solution is just to detect windows and run a DOS command directly: 

`os.system('rmdir /S /Q \"{}\"'.format(directory))`

**Comment by galbramc** [comment]
I'm in meetings till 4 pm. I'll try to look at what might be going on after
that.

**Comment by bqpd** [comment]
Oops, just noticed that mosek_cli does use rmdir...pushed a switch to rmtree and am crossing my fingers...

**Comment by bqpd** [comment]
Nope, looks like `rmtree` (which implements a find-and-delete-all-files bit) doesn't cut it. There might be a read only file in there?

**Comment by bqpd** [comment]
It seems to be working on Windows now, with a manual permissions check. But it also seems to not be installing the MOSEK bindings and just using the CLI interface...

**Comment by bqpd** [comment]
Okay, so the problem now is just in building MOSEK:
`collect2.exe: error: ld returned 1 exit status`

**Comment by galbramc** [comment]
Yes it looks like it fails to build the binding. You are printing this
error: # Failed building mosek. I have to log into the machine to see if I
can get the actual compiler error message. I'm still in the meeting.

**Comment by galbramc** [comment]
I wonder if it's a 64 vs 32 bit issue. I think I installed the 64 bit
version of anaconda, and mingw might be 32 bit.

**Comment by bqpd** [comment]
Or this: 

```
c:/mingw/bin/../lib/gcc/mingw32/4.8.1/../../../../mingw32/bin/ld.exe: cannot find C:\Program Files\Mosek\7\tools\platform\win64x86\bin: Permission denied
C:\Program Files\Mosek\7\tools\platform\win64x86\bin\mosek64_7_1.dll: file not recognized: File format not recognized
```

**Comment by bqpd** [comment]
(the latter of which could be a 32/64 bit issue)

**Comment by bqpd** [comment]
Closing this issue. If appropriate we can open a new one for building MOSEK...
