### ISSUE TITLE
standardizing method names

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#224]
proposal:

* rename function `enableUnits()` --> `enable_units()`
* rename function `disableUnits()` --> `disable_units()`
* create functions `enable_signomials()` and `disable_signomials()`, to replace current practice of modifying the module-level boolean variable `gpkit.enable_signomials`.

**Comment by bqpd** [comment]
Sounds good to me.

**Comment by whoburg** [comment]
Implemented in #228. Forgot to build the docs, resulting in #231, but that's now fixed.
