### ISSUE TITLE
refactor GP

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#226]
The methods of a GP should not modify or use its attributes as casually as they do at present. This made #180 possible. Related to #190.

Below discussion summarized in checkboxes:
* [x] methods of a GP should not modify or use its attributes as casually as they do at present
* [x] `Model` should also be refactored
* [ ] some of the functionality in `_parse_result`, `_solve`, `_run_solver`, etc could be made into functions external to the GP class
* [ ] better documentation for `_parse_result`, `_solve`, and `_run_solver`
* [x] test added in cee7879 should be replaced with tests that target modular functions developed under this ticket
* [ ] Eliminate pylint warnings about attributes being defined outside of `__init__`

**Comment by whoburg** [comment]
Great! Also looking for chances to make things more modular. For example, I wonder whether some of the functionality in `_parse_result`, `_solve`, `_run_solver`, etc could be made into functions external to the `GP` class (much easier to unit test!) with the implementation of those class functions then a simple call to the external function. All these internal functions need better documentation too.

I see the modularization as key because different subsets of these methods are needed for extensions we're building, like SP, or friendly feasibility, etc.

**Comment by bqpd** [comment]
Good point!

**Comment by whoburg** [comment]
Before closing this issue, the test added in cee7879da7b37c8fda755eb85446394a7710d4de should be replaced with more specific unit tests that target each modular functionality developed under this ticket.

**Comment by whoburg** [comment]
Started toying with fixing pylint issues in 6feb52522475a2f064aa80169b8369cf27d8eb1d. Getting a lot of warnings/errors about attributes being defined outside of `__init__` (which I didn't attempt to fix).

Assuming `Model` will be refactored as part of the `GP` refactoring.

**Comment by bqpd** [comment]
Yup.

**Comment by whoburg** [comment]
Added todo checkoffs in original post. @bqpd are you already working on this in a private branch?

**Comment by bqpd** [comment]
Nice! I did some frankenstein stitching to get an idea of what it could look like, but nothing worth pushing; want to start over incrementally & keep the tests running for most changes.

**Comment by bqpd** [comment]
The test in cee7879 is now solvable as a GP (with the difference dealt with at the substitution stage), so I'm not sure that the checkbox above is still relevant?

**Comment by bqpd** [comment]
The only attributes defined outside of __init__ are now partial results during a solve; not sure if they still give the pylint errors?

**Comment by bqpd** [comment]
Anyway, @whoburg, make sure to check these out during / after the code review!

**Comment by whoburg** [comment]
And what was the outcome on the other two checkoffs, about `_parse_result`, `_solve`, and `_run_solver`?

**Comment by bqpd** [comment]
__run_solver got shrunk a lot, folded in GeometricProgram. Parse result is not as bad as it used to be, could still be pulled into a separate function. _solve is now just the sweep goodness, so I'm not as sure it'd be useful to pull out?

**Comment by whoburg** [comment]
Checked off attributes outside init checkbox, looks good.

I can no longer find `_run_solver` - I assume this is now inside `GeometricProgram.solve`? (sounds good, and docstring looks good)

Should the sweeping goodness in `Model._solve` be moved to another method for clarity?

`Model.parse_result could use a docstring`.

**Comment by bqpd** [comment]
In #331, parse_data is moved outside. Then I went a bit overboard and moved lots of things around.

**Comment by bqpd** [comment]
I don't think it makes much difference if sweep is in _solve or is its own function...does anyone want to step individually through their sweep?

**Comment by whoburg** [comment]
No, I was only noticing that a method called `_solve`, which I wouldn't initially expect to have much to do with sweeps, spends most of its time worrying about sweeps.

But I'm fine with it as is if you think that's best.

**Comment by bqpd** [comment]
Hmm, that's true. I think it's fine for now, though.
