### ISSUE TITLE
'git pull' Giving Extra Text

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#230]
Pretty sure this is just my awful knowledge of github showing, but when I try to pull, I get this:

```
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> origin/macbuildfixes
```

I think this has something to do with what @bqpd did to my machine on Thursday.  As far as I know, I'm not on a branch, and I don't want to mess up the master branch by doing something dumb...

**Comment by bqpd** [comment]
What's `git status` return?

**Comment by cjk12** [comment]
`#On branch origin/macbuildfixes
nothing to commit, working directory clean`

Ok, so I'm on a branch, but I didn't see it on the github when I looked.  Also, I don't know how to get back on master...

**Comment by bqpd** [comment]
Oops, that's definitely my mistake.

Try `git checkout master` and then `git pull`

**Comment by cjk12** [comment]
Yup, there we go.  Thanks.
