### ISSUE TITLE
Read The Docs Examples should be Unit Tests

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#232]
At some point, everything we have online should be included in the unit tests.  Stems from issue #231

**Comment by whoburg** [comment]
@bqpd, I know we discussed this early on. Is it true that read the docs currently runs all embedded examples? I agree further coordination of tests and docs would be good, especially after dealing with things like b1e0a4324d361b23193d16284998efe2b9509887.

@cjk12, note that in this case linked tests/docs would surprisingly not have solved the problem, as the docs had been updated in the gpkit repository. They just hadn't been re-built by read the docs. Good reminder that I should have pressed the rebuild button after changing them.

**Comment by cjk12** [comment]
Ah, that makes sense.

I'll let you two continue discussing coordination and you guys can close the issue when satisfied.

**Comment by bqpd** [comment]
Building the docs doesn't run embedded code at present, unfortunately.

**Comment by whoburg** [comment]
Would the easiest approach be to create a unit test module that simply runs every example and makes sure nothing is raised?

**Comment by bqpd** [comment]
I've been writing the advanced command examples in the docs as I write unit
tests for them, but one has to remember to keep them in sync.

Alternately, we could move the docs folder inside of the gpkit folder
(letting readthedocs know) and I think directly quote segments of the code
from the docs?

-Ned

**Comment by bqpd** [comment]
I'm liking ^ that idea more and more.

**Comment by whoburg** [comment]
That sounds cool!

**Comment by bqpd** [comment]
So, is it alright with everyone if we move the docs folder inside the gpkit folder?

**Comment by whoburg** [comment]
This is fine by me.

**Comment by whoburg** [comment]
also address the simple flight example

**Comment by whoburg** [comment]
what's the plan for this re: 0.3.2?

**Comment by bqpd** [comment]
Still planned! I was busy moving bio lab equipment all day.
