### ISSUE TITLE
N Dimensional Variables

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#237]
So, I have been working on some Trefftz Plane code in matlab, and I'd really like to have N Dimensional variable capability in GPkit.  This would be useful for something like tensors.  I'm actually storing a really complicated set of vectors that results in a 3D matrix that is (N-1)x(N)x(2).  I'm thinking the declaration should be something like:

``` python
A = ArrayVariable([2,2,2], "A", "-", "Array Variable")
```

would create a 2x2x2 variable.

**Comment by cjk12** [comment]
`from gpkit import arrayVars`
``` python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-61a2de1f5a30> in <module>()
----> 1 from gpkit import arrayVars

ImportError: cannot import name arrayVars
```

**Comment by bqpd** [comment]
It was a pull request on github. Just got merged with master, try it now.

**Comment by cjk12** [comment]
I'm getting up to date...

**Comment by bqpd** [comment]
Pull again, sorry.

**Comment by bqpd** [comment]
VectorVariable and ArrayVariable are identical right now, btw.

**Comment by cjk12** [comment]
Got it.  Wait, so I can't implement as above?

**Comment by bqpd** [comment]
Naw, you can. Pull now.

**Comment by cjk12** [comment]
Sweet.  I'll test run it and see what happens.

**Comment by bqpd** [comment]
```python
In [2]: A = ArrayVariable([2,2,2], "A", "-", "Array Variable")

In [3]: A.sum()
Out[3]: gpkit.Posynomial(A_(0, 0, 0) + A_(0, 0, 1) + A_(0, 1, 0) + A_(0, 1, 1) + A_(1, 0, 0) + A_(1, 0, 1) + A_(1, 1, 0) + A_(1, 1, 1), units='-')
```
