### ISSUE TITLE
Shortcuts for Variable etc?

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#244]
Built-in equal-length shortcuts `Var`, `Vec`/`VcV`, and `Arr`/`ArV`, or `Variable`, `VecVarbl`, `ArrVarbl` would make code look a bit nicer and life easier for expert users.

**Comment by cjk12** [comment]
As mentioned in #241, I like having the different lengths, but certainly would not oppose these shortcuts from being alternative options.

**Comment by whoburg** [comment]
Why not just do `from gpkit import Variable as Var`?

**Comment by bqpd** [comment]
That takes three lines of import code! :p

I want to do `from gpkit import *` and roll with it.

**Comment by whoburg** [comment]
Would `from gpkit.shortcuts import *` (or similar) serve the purpose? I feel it's nice to keep `dir(gpkit)` as simple as possible, though I admit I don't have a clear reason.

This isn't a super-important decision for me, so if the above suggestion doesn't work and the shortcuts would be really valuable, fine to implement.

**Comment by bqpd** [comment]
Oh I like that a lot. Any objections to adding a `gpkit.shortcuts` bit?

**Comment by whoburg** [comment]
This is complete, correct?

**Comment by bqpd** [comment]
Yup! I'll put it in a PR.

**Comment by whoburg** [comment]
Isn't already on master, per 005ff72577c284d8fcf265dd7f14e5c83a4f9ee7?

**Comment by bqpd** [comment]
Whoops, yes. :-/
