### ISSUE TITLE
PosyArray.sum and posyArray.prod don't act like numpy sum/prod

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#245]
continuation from #241 

* [x] `PosyArray` inherits from `np.ndarray`, so one would expect the following to work (currently commented-out in tests/t_vars/TestArrayVariable/test_sum):

```python
    def test_sum(self):
        x = ArrayVariable((2, 3), 'x')
        rowsums = x.sum(axis=1)
        self.assertTrue(isinstance(rowsums, PosyArray))
        self.assertEqual(len(rowsums), 2)
        colsums = x.sum(axis=0)
        self.assertTrue(isinstance(colsums, PosyArray))
        self.assertEqual(len(colsums), 3)
```

* [ ] Most of the tests under TestArrayVariable should probably be moved to t_posyarray/TestPosyArray.

**Comment by bqpd** [comment]
Ah, good point. I think I implemented a custom sum / prod so they wouldn't return 0-d arrays? But feel free to delete the relevant lines in posarray.py and see if that breaks anything...

**Comment by bqpd** [comment]
Is moving the tests the only thing remaining?

**Comment by whoburg** [comment]
Affirm.

**Comment by bqpd** [comment]
10-4
