### ISSUE TITLE
y.left and y.right zero behavior

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#247]
So this:

```python
y=VectorVariable(N,"y")
y.left
```
currently produces:
```python
[0, y_(0,), y_(1,), y_(2,)]
```

My understanding is that this is to try to neaten up the code.  However, I would find it more useful I think if this or a similar command produced the equivalent of `y[0:-1]`.  Here that would be:

```python
[y_(0,), y_(1,), y_(2,)]
```

So, particularly @whoburg , could you explain the rational behind the leading zero and comment on the usefulness of my proposed feature?

**Comment by cjk12** [comment]
Note that similar logic explains the y.right feature.

**Comment by whoburg** [comment]
Good question.

The point of `y.left` and `y.right` is places where one wants a shifted view of the array, keeping the same length. Of course, something has to be done on the boundary, and so we add the zero.

Great example application is a spatial discretization, e.g.

```python
from gpkit import VectorVariable
N = 5
y = VectorVariable(N, 'y', 'm', 'bin midpoints')
dy = VectorVariable(N, 'y', 'm', 'bin widths')
constraints = [y >= y.left + dy.left/2. + dy/2]
```

Using slicing, the equivalent but uglier formulation would be:
```python
constraints = [ y[1:] >= y[:-1] + dy[:-1]/2. + dy[1:]/2,
                y[0] >= dy[0]/2. ]
```

For `y[0:-1]`, I suggest using exactly that -- `y[0:-1]` -- nice and readable.

**Comment by cjk12** [comment]
Ok, so I believe most of what I'm doing at the moment requires the reduction of a dimension, so I'm probably going to stick with slicing syntax in place, but keep in mind this feature for future applications.
