### ISSUE TITLE
if statements constraints

### ISSUE THREAD

**Issue by cjk12** [convexopt/gpkit#248]
How would we do this in GPkit:

```python
N=5
y = VectorVariable(N, "y")

if y.size() == 4:
    y[3] == 1
elif  y.size() == 5:
    y[4] == 1
else:
    y[0] == 1
```
And use this to enforce a constraint?  At issue here is that an if-elif-else statement cannot be written as a one line statement because apparently it violates PEP-8 as per:
http://stackoverflow.com/questions/14029245/python-putting-an-if-elif-else-statement-on-one-line

and to my knowledge, there is no way to use multiple lines to do a constraint.  Hence, my use of single line nested for loops, a la:
```python
[[ ((y[i]-y2[j])**2 + (z[i]-z2[j])**2)*grad_phi[i,j,0] >=  (z[i] - z2[j]) for j in range(1,Np)] for i in range(1,N)],
```
which works, but looks terrible...

**Comment by bqpd** [comment]
The pythonic way to write that last one is:

```python

[ [ ((y[i]-y2[j])**2 + (z[i]-z2[j])**2)*grad_phi[i, j, 0] >= (z[i] - z2[j])
    for j in range(1, Np)]
    for i in range(1, N)],
```
or
```
python
eqns = []
for j in range(1, Np):
    for i in range(1, N):
        squared_dist = (y[i]-y2[j])**2 + (z[i]-z2[j])**2
        left_side = squared_dist * grad_phi[i, j, 0]
        eqns.append(left_side >= z[i] - z2[j])
```

**Comment by cjk12** [comment]
Ok, so that makes my for loops nicer, but does not address the fundamental if statement problem.

**Comment by bqpd** [comment]
Oh, sorry.

**Comment by bqpd** [comment]
see http://www.pythoncentral.io/one-line-if-statement-in-python-ternary-conditional-operator/

```python
N=5
y = VectorVariable(N, "y")

constraint = 1 == (y[-1] if N in [4, 5] else y[0])
```

**Comment by cjk12** [comment]
Sigh...  Once again we are missing the point :p  My actual example is significantly more complicated than that contrived example:

```python
    for i in range(1,N):
        if z2[i+1]-z2[i] == 0 :
            n[i,1] = 0
            n[i,2] = 1
        elif y2[i+1]-y2[i] == 0 and y2[i] < 0 :
            n[i,1] = 1
            n[i,2] = 0
        elif y2[i+1]-y2[i] == 0 and y2[i] > 0 :
            n[i,1] = -1
            n[i,2] = 0
        else :
            n[i,1] = -1/(y2[i+1]-y2[i])
            n[i,2] = 1/(z2[i+1]-z2[i])

        if n[i,2] < 0 :
            n[i,1] = -n[i,1]
            n[i,2] = -n[i,2]
```

So I cant do that convenient indexing trick...

**Comment by bqpd** [comment]
Sooo....<scratches head> are you asking for a case statement? Let's deal with this in lab meeting.

**Comment by cjk12** [comment]
Yea, I guess it could be rewritten as a case statement.  Believe me, there is a really good reason for doing this haha.  Lab meeting sounds great.
