### ISSUE TITLE
Substituting for a single element of a PosyArray

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#267]
What is the best-practice syntax/method for substitutions on a single element of an existing `PosyArray`? Looking for a simple example to add to the docs.

**Comment by bqpd** [comment]
from gpkit import VectorVariable
v = VectorVariable(3, "x")
v[0] = v[0].sub(v[0], 3)

**Comment by whoburg** [comment]
Any thoughts on overriding `Variable.sub` so that

```python
x = Variable('x')
subbed = x.sub(3)
```

works?

**Comment by whoburg** [comment]
bump

**Comment by bqpd** [comment]
Subbed would be x with "value=3" in the descr, or would it just be 3?

**Comment by whoburg** [comment]
Well, the proposal would be for `Variable('x').sub(3)` to be equivalent to `Variable('x', value=3)`. Seems really clean from a user interface perspective, but maybe it's not worth it if it requires a major refactor?

**Comment by bqpd** [comment]
Naw, that'd be easy!

**Comment by bqpd** [comment]
Turns out this isn't easy, because we currently assume that anything that inherits from Signomial uses its method of substitution. We could add a 'value' method instead?

**Comment by whoburg** [comment]
I mistakenly glossed over the distinction between `Variable('x', value=3)` and `Monomial(3)`. Note that `Variable('x').sub({'x': 3})` currently returns `Monomial(3)`, which I'm fine with. My intent was simply to enable `Variable('x').sub(3)` as a shorthand, which works only for Variable objects, since they have a single `VarKey`.

I've implemented and tested this on the sub_improvements branch in 5e59f2adc73b8443e3e0582e8bc8d159810a5567.

**Comment by bqpd** [comment]
Oh! Looks good, then.

I was thinking of `x.sub(3)` as a shorthand for `x.varkeys.values()[0].descr["value"] = 3`, which could serve as an alternative to passing around dictionaries of substitutions...but on second thought I think dictionaries are better.

**Comment by whoburg** [comment]
just looked up this ticket for a use case where I'd really like to fix an element of a VectorVariable to 0. I think it'd be convenient to implement @bqpd's last suggestion, so that one can do

`x.setto(4.3)`  # set's the value of x to 4.3; mutates x.

Is that straightforward or does the race condition problem resurface here?

**Comment by bqpd** [comment]
For a vector variable, is it ever going to have a nonzero value? If not, I'd just replace that element of the array with a 0...
