### ISSUE TITLE
Signomial programming heuristic should expose single-step method

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#271]
It should be possible to do a single step of the signomial programming heuristic and get back the corresponding GP approximation, residual, solution, etc.

Public `local_solve` method would then be a simple while loop wrapper around the above.

Overall theme is making everything more modular.

Related to removing code duplication between `GP` and `SP`.

**Comment by bqpd** [comment]
It does in the refactor! 

```python
import gpkit
x = gpkit.Variable('x')
y = gpkit.Variable('y')
gpkit.enable_signomials()
m = gpkit.Model(x, [x+y >= 1, y <= 0.1])
sol = m.localsolve(verbosity=0)
print m.program.gps
```
