### ISSUE TITLE
Reduce use of side effects

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#272]
Methods and functions with side effects should be clearly documented. Goal of this ticket is to create documentation in places where side effects need to happen, and remove side effects (i.e. don't modify class attributes) as much as practical.

Related to #226.

**Comment by bqpd** [comment]
The refactor does this pretty well! They're used in SPs and GPs only to record solver results and progress before potentially erroring on their verification.

**Comment by bqpd** [comment]
Waiting on @whoburg's code review to close this one.

**Comment by bqpd** [comment]
Removed some more from Model

**Comment by whoburg** [comment]
How much time would it take to document all current instances of side effects in method docstrings?

**Comment by bqpd** [comment]
Will do!
