### ISSUE TITLE
getting raw solver output

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#277]
Moving e-mail conversation to an issue. Want a way to view/obtain raw output from solvers.

@pgkirsch:
...Do we want to add being able to see the number of solver iterations as a feature,...? 

For my own future reference (and for anyone else who doesn’t know/has forgotten how to do this) I’m including how I found the number of mosek iterations. Please let me know if there is a neater way that I missed. The only method I could figure out how to see the number of iterations was to add the following line before the return statement in `gpkit._mosek.expopt.printcb()`

`print msg[:-1]`

which printed the full solver log to the command line (big thank you to whoever wrote the docstring for `printcb`). Maybe the potential feature I mentioned above could be as simple as an optional argument to `solve()` that switches the statement above on?

@whoburg:
Yes, agreed we want this feature. @bqpd may have suggestions on implementation, but what you outlined sounds like a great start. Note we have to make sure it works cleanly independent of which solver is being used.

@bqpd:
Uncommenting that line seems like the right way to go! Ideally this would be controlled by the "settings" dictionary that is passed to the solver-function-constructor.

In particular, the MOSEK stream messager could have filters or flags of what to print, from everything (what you did) to nothing (the commented-out default).

**Comment by bqpd** [comment]
Haha, @pgkirsch, I remember debugging the MOSEK integration and writing that docstring.

**Comment by whoburg** [comment]
I prefer simplicity as a starting point, so for now I'd vote for any solver output being handled as one giant string. Any further parsing could be handled by a separate parsing module, if that's needed.

**Comment by whoburg** [comment]
To clarify, I'm talking about any messages the solver prints being handled as one giant string. We would of course get solution values, status, etc from the solver API, as opposed to parsing it from text.

**Comment by bqpd** [comment]
Sounds good to me! @pgkirsch, what are your thoughts?

**Comment by pgkirsch** [comment]
Sounds fine to me too. It doesn't seem necessary to sink a bunch of time into something like this so I'm all for the simplest option.

**Comment by pgkirsch** [comment]
@bqpd when you mentioned the stub code in `geometric_program.py` were you referring to the `solver_out` stuff?

Also what do you mean by stream debugger in this context?

**Comment by bqpd** [comment]
yup! that Mosek debugger that gets live updates from the Mosek solver is a "stream debugger". I think we can get that kind of live output from all of our solvers...

**Comment by bqpd** [comment]
@pgkirsch, let me know if you need any more notes on my poorly commented code for this :p

**Comment by pgkirsch** [comment]
Sorry, I don't follow...

So the proposed idea is to make `solver_out` include more of the output that `print msg[:-1]` (inside the `solverfn`) gave me?

**Comment by bqpd** [comment]
I was thinking of making a new `self.solver_log` attribute which would be a list of those outputs, in order.

**Comment by pgkirsch** [comment]
Wait which outputs (plural)? I thought we decided on having just one big string as the simplest solution.

**Comment by bqpd** [comment]
That'd work too!

**Comment by pgkirsch** [comment]
c pointer code is confusing.

is there a way to pass arguments to `printcb`?

**Comment by pgkirsch** [comment]
Oh wait never mind ignore that

**Comment by pgkirsch** [comment]
Any suggestions for how to convert a `'gpkit._mosek.lib.expopt_h.String'` object to a regular string so I can print to a file using `write()`?

**Comment by bqpd** [comment]
(print to a file?)

Does `str(object)` work?

**Comment by pgkirsch** [comment]
Oh it does, whoops.

My current method involves writing a log file (e.g. `mosek.log`) that contains the solver output if the user specifies that this is something they want. Is this a desirable/undesirable/indifferent approach?

**Comment by bqpd** [comment]
Hmm, yes. Why not just save it to the variable gp.solver_log?

**Comment by pgkirsch** [comment]
2 reasons:

1. I'm not sure I know how to pass `msg` out of weird c-pointer-function-handle-callback-MSK.streamfunc land.

2. why pass it all the way back up to geometric_program.solve(), if all you are going to do with it there is either print to screen or write a log file, when you could both of those things within `printcb`?

**Comment by bqpd** [comment]
Make an argument to .imize that's the list, and append to in that function.

**Comment by pgkirsch** [comment]
argh sorry struggling with this..... by that function you mean `printcb` right? is everything in `imize` supposed to be in scope for `printcb`?

**Comment by pgkirsch** [comment]
Anyway surely it would be an attribute of `sol (= gp.solve())` as opposed to an attribute of a `gp`

**Comment by bqpd** [comment]
As an attribute of a gp, though, you can access it even if the solve fails.

**Comment by pgkirsch** [comment]
Yeah you're right, I see why it's a good idea

**Comment by pgkirsch** [comment]
I can't figure out for the life of me how to append `msg` to a list. Any help appreciated.

**Comment by bqpd** [comment]
`.append(msg)`?

**Comment by pgkirsch** [comment]
I edited this after I posted the question but I'm stuck on the scope issue not the actual appending

**Comment by bqpd** [comment]
Oh, sorry! Maybe declare `printcb` in `imize`?

**Comment by whoburg** [comment]
this may be a big help with debugging #217 !

**Comment by pgkirsch** [comment]
mmmm still no luck with passing a list to/from `printcb`. As far as I can tell you can't change the arguments to `printcb` because it has to follow the format given. Meanwhile, declaring it inside `imize` doesn't seem to help either. `printcb` doesn't really get called anywhere per se.... right?

**Comment by pgkirsch** [comment]
Suggestion to self for later: use casting. (ref: http://stackoverflow.com/questions/318067/python-converting-strings-for-use-with-ctypes-c-void-p/318140#318140)

**Comment by bqpd** [comment]
Super sorry to swoop in like this, but I've got an idea for this that might also mean we don't need `.gpkit`

**Comment by bqpd** [comment]
@pgkirsch, let me know if the changes in df82cbbedfa9070db40aad65443b2067cea4d99d make sense, I'm happy to explain them!

**Comment by pgkirsch** [comment]
Ooooh I think I see what you did...clever!  .. ..And don't be sorry, I'm grateful that you once again covered for my incompetence.

**Comment by bqpd** [comment]
It turns out that `cvxopt` is really poorly done in this regard and it would have been impossible to get logs from it any other way...

**Comment by whoburg** [comment]
that makes me wonder, (for a future release, of course) -- are we similarly "really poorly done in this regard"?

**Comment by bqpd** [comment]
Nope; everything printed is also stored in a user accessible data structure.

**Comment by bqpd** [comment]
Erps that was fun. Let's let the PR close it.
