### ISSUE TITLE
substitution fails simple test

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#279]
I'm surprised our unit tests haven't caught this. Minimum working example:

```python
from gpkit import Variable
x = Variable('x')
y = Variable('y')
p = 1 + x**2
q = p.sub({x: y**2})
assert q == (1 + y**4)
```

output:
```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-db08612a9cfb> in <module>()
      3 y = Variable('y')
      4 p = 1 + x**2
----> 5 q = p.sub({x: y**2})
      6 assert q == (1 + y**4)

.../gpkit/nomials.pyc in sub(self, substitutions, val, require_positive)
    169         varlocs, exps, cs, subs = substitution(self.varlocs, self.varkeys,
    170                                                self.exps, self.cs,
--> 171                                                substitutions, val)
    172         return Signomial(exps, cs, units=self.units,
    173                          require_positive=require_positive)

.../gpkit/substitution.pyc in substitution(varlocs, varkeys, exps, cs, substitutions, val)
    147                 varlocs_[sub].append(i)
    148             elif isinstance(sub, Monomial):
--> 149                 if isinstance(var.descr["units"], Quantity):
    150                     try:
    151                         new_units = var.descr["units"]/sub.units

KeyError: 'units'
```

This appears to come from trying to look up `var.descr["units"]` when `var` has no units. I see two possible resolutions:

1. Force all `VarKey` descrs to have a `units` attribute.
2. Don't try to look up `var.descr["units"]` without confirming it exists, or otherwise refactor the approach.

@bqpd, any thoughts? 

Todos:
* [x] Decide on option 1 or 2 above
* [x] Implement
* [x] Add unit test (at least the MWE above)
* [ ] The `substitution` function looks like it could use a refactor.

**Comment by whoburg** [comment]
Related to #273

**Comment by whoburg** [comment]
Let's work on this on the `sub_improvements` branch under #270.

**Comment by whoburg** [comment]
I'm leaning slightly toward option 1. In particular, we would make `units` a first-class attribute of all `Signomial` objects (and therefore of all `Variable` objects by inheritance). This would enable stuff like the following to always work:

```python
if v.units:
    print "The units of v are %s" % v.units
else:
    print "v is dimensionless"
```

Anyone have any other opinions or seconds?

**Comment by whoburg** [comment]
Haven't tried this fix, but it looks to me like we could adopt a variant of option 2 above, where we simple replace `var.descr["units"]` with `var.units`.

**Comment by bqpd** [comment]
That could work, and give everything a unit.

**Comment by whoburg** [comment]
Ok, proposed fix for 3 out of 4 checkboxes pushed to branch over at #270

**Comment by bqpd** [comment]
What makes you think `substitution` could use a refactor?

**Comment by whoburg** [comment]
A few things: 

 - `getsubs` and `vectorsub` are undocumented and confusing (they seem to have similar roles, but one returns something, and the other operates by side effect)
 - In #273 we discussed that functions involving varlocs, exps, cs, should perhaps be implemented as part of a renamed `PosyTuple`
 - A lot of repeated code, e.g. under `elif isinstance(sub, VarKey)` vs `elif isinstance(sub, Monomial)`.
 - "too-many-branches" warning from pylint -- feels like a maze of conditionals...

**Comment by whoburg** [comment]
I'm going to copy the above to a new issue, since this one is closed -- we can of course close it if we decide it shouldn't exist.

**Comment by bqpd** [comment]
Sounds good! Some amount of this is attempting to do typed programming in Python. :-/ Which would be great to fix, I'm just not sure how.
