### ISSUE TITLE
Setting variables to zero

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#290]
As a user, I sometimes want to set variables in a problem to zero. I'm working on one right now -- I have a 3-segment mission defined by three parameters: R_outbound, T_loiter, and R_return. I want to try setting T_loiter to zero (including inside a widget). GPkit is willing to substitute 0 for T_loiter. But other variables in the problem, such as the loiter fuel weight, no longer have a lower bound. The solution where those variables become 0, however, makes physical sense.

Here is a minimum working example of substituting zero for a variable. GPkit substitutes 0 for `y`, the problem remains well-posed, and the optimal solution (with cost 4) is found.

```python
from gpkit import Variable, GP
x = Variable('x', value=4)
y = Variable('y', value=0)
z = Variable('z')

prob = GP(z, [z >= x + y])
sol = prob.solve()
print sol.table()
```

But here's an equivalent problem, with `y` masked by a dummy variable `t`:

```python
from gpkit import Variable, GP
x = Variable('x', value=4)
y = Variable('y', value=0)
z = Variable('z')
t = Variable('t')

prob = GP(z, [z >= x + t,
              t >= y])
sol = prob.solve()
print sol.table()
```
This results in a `t has no lower bound` warning, and the problem is not solved (solution status: unknown). Mathematically, the argument could be made that this is not a well-posed GP. But from a user's point of view, the solution (x=4, y=0, z=4, t=0) seems perfectly valid.

It's not always practical to require the modeler to move all the zero variables to posynomials, because they might appear in a long chain of monomial constraints, inside other models, etc. So it would be nice to have methods for automatically dealing with this.

We should be careful proceeding down this path, to make sure we retain our rigorous mathematical definition of what constitutes a valid GP. For now, I'm suggesting we implement a method, 

`gp_out = replace_unbounded_below_variables_with_zero(gp_in)`,

(better names desperately needed) that takes in a GP, substitutes zero for all unbounded below variables, recursively, until there are no unbounded below variables, (and removes constraints of the form 0 <= 0 if that's not already happening), and returns another GP. This could of course also be made a method of `GeometricProgram` that mutates the object in place, and could be default behavior inside `solve`, if we decide so. But for now, let's just get the capability in place so users can call it right before `solve()` and then sub zeros at will.

**Comment by bqpd** [comment]
This sounds good! The refactor removes 0 constraints automatically, so the constraint would be properly removed; mosek can still solve with an unbounded t in the other constraint, but it zeroes the dual solution, and cvxopt can't do it.

**Comment by bqpd** [comment]
Unfortunately this opens the possibility for a c value of `nan`.

**Comment by whoburg** [comment]
Do you have an example of the c value of `nan` issue?

**Comment by bqpd** [comment]
That main example: y and t are both 0, 0/0 is nan

**Comment by bqpd** [comment]
I decided to just drop posynomials with only nan coefficients

**Comment by whoburg** [comment]
I hear @bqpd is back at work on this !

**Comment by bqpd** [comment]
Kinda? I'm having Model run this on itself before solving.

**Comment by whoburg** [comment]
cool - feel free to re-close if it makes sense -- just wanted to record the connection.

**Comment by bqpd** [comment]
:+1:
