### ISSUE TITLE
display units in slider widgets

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#291]
Low-priority feature request: it would be nice if slider widgets displayed units, either on the left hand side with the variable name/key, or on the right hand side with the value.

Unfortunately both appear a bit non-straightforward to implement; discussion welcome on ideas for doing this cleanly.

**Comment by bqpd** [comment]
This should be totally doable if we can just generate the units as a fixed string.

Having a quantity scale from milli- to kilo-, though, would require some work...

**Comment by whoburg** [comment]
Agreed it's totally doable (and I'm suggesting the straightforward implementation where units are constant for a given slider (no milli- to kilo- stuff)).

Thinking about this again I think I see how we could implement. The current implementation has a dict corresponding to the widgets (keys are strings or VarKeys; values are ranges), and then the callback from the widget can simply call `gp.sub(**kwargs)`. The two things we need to somehow implement to get units in the widgets are, roughly:

 - [ ] Translate string keys in `ranges` to `VarKeys`, so that units are accessible.
 - [ ] Make `VarKey.__str__` print a unit in this situation. But I'm a little foggy on how to do this without making units show up all over the place where we don't want them printed...

**Comment by whoburg** [comment]
potentially a stretch goal, but leaving in 0.4.0 for now.
