### ISSUE TITLE
document object hierarchy

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#294]
two flowcharts from @bqpd  ISMP2015 talk would be great addition to read the docs.

**Comment by bqpd** [comment]
![inheritance](https://cloud.githubusercontent.com/assets/1482776/8818205/568b1c8e-2ff3-11e5-863f-546c49b4f3e4.png)

![solve](https://cloud.githubusercontent.com/assets/1482776/8818209/5bd4be16-2ff3-11e5-8087-feb5b622e68b.png)

**Comment by whoburg** [comment]
Where should this go? Perhaps at the bottom of the "Basic Commands" page?

**Comment by bqpd** [comment]
Hmm, or maybe a GPkit 101 to match the Geometric Programming 101? Some kind of conceptual overview...

**Comment by whoburg** [comment]
Yeah, that sounds great!

**Comment by bqpd** [comment]
Up at http://gpkit.readthedocs.org/en/latest/gpkit101.html
