### ISSUE TITLE
nans should not appear in GPSolutionArray

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#302]
Carry over from #298.

(@whoburg): 
- [x] I'd be in favor of raising exceptions long before table printing if there are any nans, 
- [ ] and therefore removing the fix in 1238df57a7059f390a9c332bb1e10eb75d24f4a1.

(@bqpd): good point. I haven't reached that point in the refactor. We could potentially use a sparse vector instead? I put nan there here just so it'd be obvious if something weird happened (even several steps of algebra later), which seems to have worked...

**Comment by whoburg** [comment]
Agreed - this was a good way of catching things.

I'd be in favor of keeping the current `nan` initialization, but simply adding a check after the solution array is filled in, which raises an Exception if any nans remain.

This would retain the current error checking but would guarantee to users that nans will never appear in a solution (unless GPkit or a solver has a bug).

**Comment by bqpd** [comment]
The refactor has an exception if there are nans; but this doesn't solve the problem of what to do with partially-free partially-fixed variables.

**Comment by bqpd** [comment]
I actually think we should keep the fix, not throw an exception, and just use "nans" to indicate "hey that was an incomplete vector".
