### ISSUE TITLE
Friendly infeasibility

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#31]
When the GP is infeasible, make sure to report:
  * How infeasible is it?
  * Which constraints are most problematic?
  * What are some constraint changes that would make it feasible?

**Comment by whoburg** [comment]
This will go in a separate module or package -- not included in initial gpkit release.

**Comment by whoburg** [comment]
c5d54b04f0dad6dafe3d8f56149cad138050124d adds an example of an infeasible GP -- copied directly from section 2.3 of the GP tutorial (though they don't mention it's infeasible!). This could be a good simple example for dealing with infeasibility.

**Comment by bqpd** [comment]
Ooh, yes. Is there a known closest feasible point?

**Comment by whoburg** [comment]
Here's a hand-coded CFP GP for that example (leaving alone the equality constraint):
```python
from gpkit import Variable, GP

# Declare decision variables
x = Variable('x')
y = Variable('y')
z = Variable('z')
s = Variable('s')

# formulate the GP directly
prob = GP(s,      # closest feasible point
          [2 <= x*s,  # constraints
           x <= 3*s,
           x**2 + 3*y/z <= y**0.5*s,
           x/y == z**2])

# Solve the CFP GP
sol = prob.solve()

# Print results table
print sol.table()
```
And here's the output:
```python
Using solver 'cvxopt'
Solving for 4 variables.
Solving took 0.0777 seconds.
              |
         Cost :  2.31
              |
              | Free variables
            s : 2.31
            x : 0.867
            y : 0.239
            z : 1.91
              |
              | Constants
              |
              | Constant sensitivities
              |
```

**Comment by bqpd** [comment]
We have the architecture now to easily do a closest-feasible solve on a failed GP solve, and return the variable / monomial / posynomial "feasibility weights".

Should we do this? If so, how would be easiest to use? @pgkirsch, I feel like you might have some opinions on this...

**Comment by bqpd** [comment]
Created a pull request with a draft version of this.

**Comment by whoburg** [comment]
Here's the output for the simple example above:

```python
from gpkit import Variable, Model
​
# Declare decision variables
x = Variable('x')
y = Variable('y')
z = Variable('z')
s = Variable('s')
​
# formulate the GP directly
prob = Model(1,      # closest feasible point
          [2 <= x,  # constraints
           x <= 3,
           x**2 + 3*y/z <= y**0.5,
           x/y == z**2])
​
prob.feasibility_report()
​```
output:
```python
Infeasibility
-------------
      overall : 2.17
   constraint : [4.7238302924085529, 1.0000000015598456, 1.0000000068173982, 1.0000000095594597, 1.0000000150314716]
```
