### ISSUE TITLE
Floating point numbers not printing correctly

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#316]
Derived from issue #274 

```
In [1]: import gpkit
Optional Python units library (Pint) not installed; unit support disabled.

In [2]: from gpkit.shortcuts import *

In [3]: gpkit.enable_signomials()

In [4]: x = Var('x')

In [5]: y = Var('y')

In [6]: J = -0.02*x + -0.02*y +  1.02

In [7]: J.cs
Out[7]: array([-0.02, -0.02,  1.02])

In [8]: J
Out[8]: gpkit.Signomial(-0.02*x + -0.02*y + 1)
```

**Comment by pgkirsch** [comment]
Minimum working example:

```
# test316.py
from gpkit.shortcuts import *
x = Var('x')
J = 0.01*x + 1.01
print J
```

Output
```
In [1]: %run test316.py
Optional Python units library (Pint) not installed; unit support disabled.
0.01*x + 1
```

**Comment by bqpd** [comment]
Related: 

```python
In [6]: x-0.999
Out[6]: gpkit.Signomial(- + x)
```

**Comment by bqpd** [comment]
There's two things going on here:

  * intentionally limited output resolution (so that you can read the whole equation)
  * when c is 1, don't print it (fails when there's no variables)

**Comment by bqpd** [comment]
I increased the number of decimal places for cs to 3 and fixed the -1 bug.

**Comment by bqpd** [comment]
(should be autoclosed when the refactor is merged)

**Comment by pgkirsch** [comment]
Thanks for doing this, I didn't realise you were working on it, but it's probably much more efficient for you to address issues like this.

What you just said raises a few questions though:
- Are all new changes going on the newgp branch?
- Do I need to be do anything differently for pull requests? i.e. does all new code go to the newgp branch?
- I am currently pulling from master. Should I be pulling from newgp instead?

**Comment by bqpd** [comment]
Yeah. Hopefully the `newgp` branch will be mergable soon! In the meantime, not a bad idea to start working from it...

**Comment by bqpd** [comment]
btw this was the change: 0c518e3a9c87c416e352c4df62e51b4d8ebd8022
