### ISSUE TITLE
Set up Jenkins web hooks

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#334]
re: https://github.com/convexopt/gpkit/pull/331#issuecomment-130450963

**Comment by galbramc** [comment]
@whoburg @bqpd Webhooks are installed and working. We can close this issue. Commands like "test this please" and commits should start the testing more or less imediately now

**Comment by whoburg** [comment]
thanks @galbramc !!

should we leave this open (with new title) to capture the off-by-one testing issue?

**Comment by galbramc** [comment]
I don't see the need to keep this issue open. Could you open my pull request again though. I have another idea I want to test to see if I can narrow down the problem.
