### ISSUE TITLE
free variable sensitivities computed incorrectly?

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#335]
Getting free variable sensitivity warnings where I don't think I should. I think this is a valid GP and the primal solution looks correct, but I don't buy the sensitivities to `R` and `M`.

```python
from gpkit import Variable, VectorVariable, Model

R = Variable('R', units="nautical_miles")
a0 = Variable('a0', value=340.29, units='m/s')
theta = Variable(r'\theta', value=0.7598)
t = Variable('t', value=10, units='hr')
T_loiter = Variable('T_{loiter}', value=1, units='hr')
T_reserve = Variable('T_{reserve}', value=45, units='min')
M = VectorVariable(2, 'M')

prob = Model(1/R,
             [t >= sum(R/a0/M/theta**0.5) + T_loiter + T_reserve,
              M <= 0.76])
_ = prob.solve().table()
```
```
Using solver 'cvxopt'
Solving for 3 variables.
Solving took 0.0536 seconds.
free variable too sensitive: S_{M_(1,)} = 2.88e-01
free variable too sensitive: S_{R} = -2.88e-01

Cost
----
 0.0005532 [1/nmi] 

Free Variables
--------------
R : 1808                    [nmi] 
M : [ 0.76      0.76     ]        

Constants
---------
 T_{loiter} : 1       [hr]  
T_{reserve} : 45      [min] 
     \theta : 0.7598        
         a0 : 340.3   [m/s] 
          t : 10      [hr]  

Sensitivities
-------------
          R : -0.2879                
 T_{loiter} : 0.2857                 
T_{reserve} : 0.2143                 
     \theta : -0.3561                
         a0 : -0.7121                
          t : -1.212                 
          M : [ 1.03e-09  0.288    ] 
```

If this is too confusing I can try to whittle down to smaller MWE.

**Comment by whoburg** [comment]
For this issue, I don't want the example above to become a unit test. Instead, let's make sure we understand what caused this and write a more targeted unit test that would have caught this.

**Comment by whoburg** [comment]
Comparing with an earlier version, most of the sensitivities seem wrong. They should be:

```python
Constant and swept variable sensitivities
-----------------------------------------
 T_{loiter} : 0.1212  
T_{reserve} : 0.09091 
     \theta : -0.5    
         a0 : -1      
          t : -1.212  
```

**Comment by bqpd** [comment]
Found the bug in mmaps

**Comment by bqpd** [comment]
Forgot to mention I fixed this in #331, in the commit ef6b9ec7a7a11ec060247abfb94aff7f5c6f9dfa.

The problem was a reordering of the exps list upon resimplification in the Signomial call in the old `form_program`. The new `form_program` calls Signomial with the argument `simplify=False`.

**Comment by whoburg** [comment]
what's the right unit test to write?

**Comment by bqpd** [comment]
I think we can make oversensitive free variables go back to raising a RuntimeWarning, and then just add this GP as a test?

**Comment by whoburg** [comment]
ok.

**Comment by bqpd** [comment]
I think that's as simple and non-applicatoin specific as you can get. :p Sometimes, certain exps reordered on simplification, but not all the time (or other tests would have caught it). Since we only care about it if it messes up sensitivities, we just check if the sensitivities are right.

**Comment by bqpd** [comment]
We could get _more_ specific and test just `mmap_simplify`?

**Comment by whoburg** [comment]
I see your point. I suppose this is an improvement in non-application-specificness over simpleflight...

**Comment by whoburg** [comment]
still need that unit test, right?
