### ISSUE TITLE
localsolve while loop not exiting when numerator and denominator both approach zero

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#336]
Pulling this issue over from the discussion on #274 

```
import gpkit
from gpkit import Model, Variable
with gpkit.EnableSignomials():
    x = Variable('x')
    z = Variable('z')
    J = 0.01*(x - 1)**2
    sp = Model(z, [z >= J])
    sol = sp.localsolve(iteration_limit=50)


#output

Beginning signomial solve.
{x: 0.099503719020998152, z: 0.0094544313448217156}
{x: 0.30858339675657204, z: 0.0070641292715984388}
{x: 0.55138385186126571, z: 0.004137253654887871}
{x: 0.7558555212372341, z: 0.0020329156059758929}
{x: 0.88772160560639424, z: 0.0008742012957197896}
{x: 0.95412334675043098, z: 0.00034540249534560776}
{x: 0.98237655634014498, z: 0.00013081534457576836}
{x: 0.99340766018349569, z: 4.86639535899045e-05}
{x: 0.99755961776297863, z: 1.7977255827085814e-05}
{x: 0.99910015431588806, z: 6.6236742434287643e-06}
{x: 0.99966868273464993, z: 2.4381000785678302e-06}
{x: 0.99987807689494357, z: 8.9711476347932211e-07}
{x: 0.99995514181077461, z: 3.3005551447630321e-07}
{x: 0.9999834968924961, z: 1.2142408125806915e-07}
{x: 0.99999392875103243, z: 4.4669889151738637e-08}
{x: 0.99999776649946515, z: 1.6433196923939157e-08}
{x: 0.99999917833933127, z: 6.0454438375448823e-09}
{x: 0.9999996977276967, z: 2.2239956551815462e-09}
{x: 0.99999988880020207, z: 8.1816243629095626e-10}
{x: 0.99999995909187633, z: 3.0098516157414271e-10}
{x: 0.9999999849507416, z: 1.1072625650178e-10}
{x: 0.99999999446368726, z: 4.0733912983436912e-11}
{x: 1.0, z: 1.0, \fbox{0}: 1.0}
{x: 0.099503719020998152, z: 0.0094544313448217156}
{x: 0.30858339675657204, z: 0.0070641292715984388}
{x: 0.55138385186126571, z: 0.004137253654887871}
{x: 0.7558555212372341, z: 0.0020329156059758929}
{x: 0.88772160560639424, z: 0.0008742012957197896}
{x: 0.95412334675043098, z: 0.00034540249534560776}
{x: 0.98237655634014498, z: 0.00013081534457576836}
{x: 0.99340766018349569, z: 4.86639535899045e-05}
{x: 0.99755961776297863, z: 1.7977255827085814e-05}
{x: 0.99910015431588806, z: 6.6236742434287643e-06}
{x: 0.99966868273464993, z: 2.4381000785678302e-06}
{x: 0.99987807689494357, z: 8.9711476347932211e-07}
{x: 0.99995514181077461, z: 3.3005551447630321e-07}
{x: 0.9999834968924961, z: 1.2142408125806915e-07}
{x: 0.99999392875103243, z: 4.4669889151738637e-08}
{x: 0.99999776649946515, z: 1.6433196923939157e-08}
{x: 0.99999917833933127, z: 6.0454438375448823e-09}
{x: 0.9999996977276967, z: 2.2239956551815462e-09}
{x: 0.99999988880020207, z: 8.1816243629095626e-10}
{x: 0.99999995909187633, z: 3.0098516157414271e-10}
{x: 0.9999999849507416, z: 1.1072625650178e-10}
{x: 0.99999999446368726, z: 4.0733912983436912e-11}
{x: 1.0, z: 1.0, \fbox{1}: 1.0}
{x: 0.099503719020998152, z: 0.0094544313448217156}
{x: 0.30858339675657204, z: 0.0070641292715984388}
{x: 0.55138385186126571, z: 0.004137253654887871}
{x: 0.7558555212372341, z: 0.0020329156059758929}
Solving took 50 GP solves and 0.828 seconds.

Cost
----
 0.002033

Free Variables
--------------
x : 0.7559   
z : 0.002033 

```

Unsurprisingly, if you set `iteration_limit=22`, the answer is correct:

```
Cost
----
 4.073e-11

Free Variables
--------------
x : 1         
z : 4.073e-11 
```

__tl;dr__ the while loop exit condition in `localsolve` doesn't seem to be doing its job.

**Comment by pgkirsch** [comment]
Fix suggested by @bqpd involves adding a small fixed value to the denominator

**Comment by bqpd** [comment]
I don't know about that, though, because it makes it not scale-invariant.

If it weren't for that infeasible last problem, this would totally work, but then the "nearest feasible" resets it...

**Comment by pgkirsch** [comment]
Yeah that's a fair point
 I will look into it some more

**Comment by bqpd** [comment]
Maybe just `if cost < 1e-10`? That's hitting the edge of numerical precision anyway...

**Comment by pgkirsch** [comment]
as another `or` clause?

**Comment by bqpd** [comment]
an and, I think? `while [...] and cost > 1e-10`

**Comment by pgkirsch** [comment]
@whoburg:
"I'm not yet personally convinced that adding `1e-whatever` is a good solution. Note further discussion at #329. We need to first figure out why things behave so differently with J in the objective vs constraints."

"I still think that SPs with optimal objective values equal to (or less than) zero might be fundamentally ill-posed. That's because the monomial approximations become ill-posed..."

**Comment by pgkirsch** [comment]
But surely you can't expect a modeler to know the optimal cost of their problem before they solve it..

**Comment by bqpd** [comment]
@whoburg, requiring the cost to be > 1e-10 exactly answers that ill-posedness

**Comment by whoburg** [comment]
@pgkirsch: "But surely you can't expect a modeler to know the optimal cost of their problem before they solve it.."

If we're working in GP/SP land, then all variables are positive (signomials cannot contain non-positive variables), so we're already expecting modelers to know something about the sign of variables. I do think it might be reasonable to require the modeler to know something about the sign of both their cost function and their constraints.

The entire SP solution algorithm is based on approximating the SP with a GP at every step. I simply can't do that if any signomial takes on a negative value. Moreover, at every step, the GP cost is an upper bound on the cost of the SP! If I have a signomial taking on a negative value, I can't upper bound it with any GP compatible function...

**Comment by whoburg** [comment]
Wow, I just realized that everything I just said is dumb, because we can split any signomial s(x) = p1(x) - p2(x) into a difference of posynomials, which do have well-defined monomial approximations.

So @pgkirsch I think you're right. I think we should be able to handle negative cost functions.

**Comment by bqpd** [comment]
What is the monomial approximation of `s(x) = p1(x)-p2(x)`?

The monomial approximation of `s(x) <= 1` is

```
s(x) <= 1
p1(x) - p2(x) <= 1)
p1(x) <= 1 + p2(x)
p1(x)/(1 + p2(x)) <= 1
```

and then we take the monomial approximation of `1 + p2(x)`

**Comment by bqpd** [comment]
Are we closing this for now with the decision to not support Signomials that approach 0?

**Comment by bqpd** [comment]
Closing; we should open a new issue about 0 signomials

**Comment by whoburg** [comment]
@bqpd I really like your comment about "what's the monomial approximation" and want to use it for further discussion.

Can you please copy exactly that comment to either #348 or a new ticket, whichever appropriate?

**Comment by bqpd** [comment]
Sure thing.
