### ISSUE TITLE
Satellite power systems example?

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#363]
@whoburg **said:** Looking for a new GP application? Satellite power systems: https://stellar.mit.edu/S/course/16/fa14/16.851/courseMaterial/topics/topic3/resource/rauschenback-solar-array-design/rauschenback-solar-array-design.pdf

**Comment by bqpd** [comment]
Should this be in the Model library repository?

**Comment by whoburg** [comment]
+1
