### ISSUE TITLE
Examples failing

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#369]
The following examples fail with latest code and need to be fixed:
- [x] `beam_bending.py`

`NameError: name 'length' is not defined`

- [x] `simpleflight.py`

`AttributeError: 'Model' object has no attribute 'variables'`

- [x] `water_tank.py` (related to issue #361)

`RuntimeWarning: Primal solution violates constraint: 21.5443469003 is greater than 1.`

**Comment by pgkirsch** [comment]
Add to make examples

**Comment by whoburg** [comment]
@pgkirsch, are you on this?

**Comment by pgkirsch** [comment]
It's on my radar but I'm not currently working on it. Should be easy so hopefully can get it done in the next day or so. Is that OK?

The beam bending example is a mess so I'm intending to redo it.

**Comment by pgkirsch** [comment]
`simpleflight` exists in both `docs/source/examples` and `gpkit/tests`. Can I go ahead and remove the one from `tests` in light of issue #232?

**Comment by whoburg** [comment]
yes, but note those two files differ, so please be sure to check out the diff and make sure everything relevant ends up in the final version.

**Comment by whoburg** [comment]
Fixed by #378
