### ISSUE TITLE
pformat calling <

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#371]
Perhaps unrelated, perhaps not, but another `repr` error:

```
from gpkit.shortcuts import *
from numpy import ones

N = 6
L = 5.
dx = L/(N-1)

EI = Var("EI",10)

P = 100
p = Vec(N, "p", descr="Distributed load")
p = p.sub(p, P*ones(N))

V  = Vec(N, "V", label="Internal shear")
M  = Vec(N, "M", label="Internal moment")
th = Vec(N, "th", label="Slope")
w  = Vec(N, "w", label="Displacement")

eps = 1E-6 #something small

substitutions = {var: eps for var in [V[-1], M[-1], th[0], w[0]]}

objective = w[-1]

constraints = [EI*V.left[1:N]     >= EI*V[1:N]    + 0.5*dx*p.left[1:N]     + 0.5*dx*p[1:N],
               EI*M.left[1:N]     >= EI*M[1:N]    + 0.5*dx*V.left[1:N]     + 0.5*dx*V[1:N],
               EI*th.right[0:N-1] >= EI*th[0:N-1] + 0.5*dx*M.right[0:N-1]  + 0.5*dx*M[0:N-1],
               EI*w.right[0:N-1]  >= EI*w[0:N-1]  + 0.5*dx*th.right[0:N-1] + 0.5*dx*th[0:N-1]]

m = Model(objective, constraints, substitutions)
```

This code doesn't generate an error on its own, but

```
In [2]: m
Out[2]: <repr(<gpkit.model.Model at 0x10441d090>) failed: TypeError: unsupported operand types for <: 'Variable' and 'Variable'>
```

**Comment by whoburg** [comment]
hmph, pformat is definitely calling `<`. Did we agree on a path to resolving this in person?

Why was it working before?

**Comment by bqpd** [comment]
< works for VarKeys, just not for variables; it's now sorting an uncoerced substitutions list

**Comment by whoburg** [comment]
Ok, so perhaps the fix is to standardize coercion to VarKeys -- I have a note to work on that already.

Can get to that after we get unit tests on #360 working.

**Comment by pgkirsch** [comment]
Another related case(?), this time with `>`:

```
In [1]: pwd
Out[1]: u'/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/docs/source/examples'

In [2]: from beam import beam

In [3]: beam(10)
Out[3]: <repr(<gpkit.model.Model at 0x1059c0890>) failed: TypeError: unsupported operand types for >: 'Variable' and 'VarKey'>
```

**Comment by bqpd** [comment]
Same issue; Variables don't support < or >

**Comment by whoburg** [comment]
Should we just not call `pformat` on the list of subs? That would resolve this.

Another approach -- we already have `NomialData._get_varkeys`, but that would mean we need a way to get the NomialData corresponding to a given Model (perhaps we want that)?

**Comment by bqpd** [comment]
Good point, we should just use a different sort key

**Comment by whoburg** [comment]
more details? I didn't follow. (my last message above was two different options -- @bqpd do you support one of them?)

**Comment by bqpd** [comment]
Oops, yep, the first.
