### ISSUE TITLE
Signomial equality seems broken

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#392]
```python
In [3]: 0 != Signomial(1)
Out[3]: False
```

Related:
```python
In [8]: with SignomialsEnabled():
   ...:     s0 = Signomial(0)
   ...:

In [9]: s0
Out[9]: gpkit.Signomial(0)

In [10]: 0 == s0
Out[10]: False

In [11]: 0 != s0
Out[11]: False
```

**Comment by bqpd** [comment]
Fixed in #391

**Comment by whoburg** [comment]
I don't love the fix in #391, because it prevents me from writing a class that doesn't have exps/cs/units, but knows how to compare itself to a nomial data.

I'm about to propose something else in another PR.

**Comment by bqpd** [comment]
Sounds good!

**Comment by whoburg** [comment]
sorry, getting distracted by too many things. I'll push what I have so @bqpd can get the idea. It fails tests right now because `Monomial.__ne__` is not implemented -- @bqpd I can get to this in an hour or so, or you can run with it if you're interested.

**Comment by bqpd** [comment]
I don't know if this actual fixes the original example...your tests didn't cover 0.

**Comment by whoburg** [comment]
aha, you're right! Because `Signomial(1)` is type Monomial, but `Signomial(0)` is type `Signomial`. I only dealt with numeric comparisons for Monomials, but that logic probably should have gone in Signomial instead.

**Comment by bqpd** [comment]
I just decided to make singlet Signomials into Monomials in that commit above...bit of a hack?

**Comment by whoburg** [comment]
yeah, I think that `Signomial(-3)` definitely needs to be type `Signomial`, not `Monomial`.

**Comment by bqpd** [comment]
But what if I want a monoeq constraint of `-3 == -Monomial("x")`?

**Comment by whoburg** [comment]
Right now, the answer is "that's a signomial equality constraint, which we don't currently support."

**Comment by whoburg** [comment]
Note we also don't support the constraint

`-1 <= -x + -x**2`

Which is of a similar flavor...

**Comment by bqpd** [comment]
Heh, true.
