### ISSUE TITLE
Returns UNKNOWN when problem is primal (or dual?) infeasible

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#399]
Warning from my code:
```
RuntimeWarning: final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.
```

But, printing the solver (MOSEK) output:
```
....'status': 'PRIM_INFEAS_CER'....
```

which is significantly more useful than `UNKNOWN`, so it should be passed on to the user.

I'm not sure if at this level this status is backwards or not (i.e. whether it actually  means dual infeasible), but I suspect the change I made would render the problem primal infeasible. Regardless, GPkit should return something more specific than `UNKNOWN`, which I have taken to be synonymous with dual infeasible.

Loosely related issues: #157 and #380

**Comment by bqpd** [comment]
(why was this closed?)

**Comment by pgkirsch** [comment]
Sorry, this was my mistake. The problem is an SP and the first GP was `PRIMAL_INFEAS`, but the second iteration did indeed have status `UNKNOWN`. For some reason I didn't notice that when I created the issue. I would have deleted the ticket altogether but Github still doesn't support deleting issues it seems..

**Comment by bqpd** [comment]
Ah, no worries! it's good to note that that's a potential user confusion.

**Comment by bqpd** [comment]
What was the problem? This is the first SP I've heard of that doesn't work
after trying a feasibility-GP (which it would have done after the first).

**Comment by pgkirsch** [comment]
I think the issue was because after the first solve, there were some pretty huge numbers in the primal:

```
RuntimeWarning: overflow encountered in exp np.exp(primal)))
```

**Comment by bqpd** [comment]
Hmm, but the first solve's results should have been ignored, replaced with
the feasible solve. Maybe the feasible solve had the overflow? I think we
should add feasible_solves to the list in .gps

**Comment by bqpd** [comment]
If you pull master the feasible gp will now be in .gps

**Comment by pgkirsch** [comment]
Thanks!
