### ISSUE TITLE
SP algorithm doesn't reach optimum (local or global)

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#400]
```python
from gpkit.shortcuts import *
from gpkit import SignomialsEnabled
A_tube = Var('A_tube', value=2) # cross sectional tube area 
A_bypass = Var('A_bypass') #  bypass cross sectional area 
A_pod = Var('A_pod') #pod cross sectional area 

with SignomialsEnabled():
    m = Model(A_pod,
             [
              A_bypass >= 0.2,
              A_tube >= A_pod + A_bypass, # Tube area relations 
              A_tube <= A_pod + A_bypass, # Tube area relations 
              A_pod >= 0.1
              ]
             )

    sol = m.localsolve()


# output ---------------------------------------------------------
Solving took 2 GP solves and 0.39 seconds.

Cost
----
 0.9998

Free Variables
--------------
A_bypass : 1      
   A_pod : 0.9998 
```

If we change the constraint on `A_bypass` to be `A_bypass <= 0.2`, the SP solves correctly:
```
Cost
----
 1.8

Free Variables
--------------
A_bypass : 0.2 
   A_pod : 1.8 
```

**Comment by bqpd** [comment]
Hmm, taking only 2 gp solves is a bit suspicious. How many does it take with the opposite constraint?

**Comment by bqpd** [comment]
cvxopt runs to the iteration limit on this one.

**Comment by pgkirsch** [comment]
4

**Comment by bqpd** [comment]
So this is weird; the primal_infeasible GP is not raising a runtime warning when solved during the signomial solve. !

**Comment by pgkirsch** [comment]
My larger problem (from which the MWE is extracted) is also only taking 2 solves, which I was actually very impressed by hah....

**Comment by bqpd** [comment]
Huh! Well in this case MOSEK solves it but cvxopt thinks it's primal_infeasible...

**Comment by bqpd** [comment]
and mosek_cli fails in `check_solution`

**Comment by pgkirsch** [comment]
why on earth would it be primal infeasible?

**Comment by bqpd** [comment]
I dunno, I can see just looking at it that mosek's getting a valid solution

**Comment by whoburg** [comment]
Simpler MWE:

```python
from gpkit import SignomialsEnabled, Variable, Model
x = Variable('x')
y = Variable('y')

with SignomialsEnabled():
    m = Model(x, [x >= .1,
                  x + y >= 1,
                  x + y <= 1])
sol = m.localsolve(solver='mosek')
```

I think we haven't thought hard about signomial equality constraints yet...  :/

**Comment by whoburg** [comment]
The behavior seems to be that our SP heuristic just sticks to the initial guess for signomial equality constraints. need to debug this

**Comment by bqpd** [comment]
Hmm! (note that this doesn't solve with cvxopt, instead returning "unknown" even as it returns the same answer after reaching the maximum number of iterations)

I think (0.5, 0.5) _is_ locally optimal. When the guess for x is equal to the guess for y, the gp approximation will work out to:

```
x >= .1
0.5 * (x*y)**-0.5 <= 1
x + y <= 1
```

let's manipulate that central constraint a bit...

```
0.25 / (x*y) <= 1
0.25 <= x*y
0.25/y <= x
```

and plug it into the last constraint:

```
0.25/y + y <= 1
0.25 + y^2 <= y
y^2 - y + 0.25 <= 0
(y - 0.5)^2 <= 0
```

the only possible solution to this is y = 0.5!

**Comment by bqpd** [comment]
If you start it at `x = 0.2, y = 0.8`, mosek moves down very very slowly...

**Comment by bqpd** [comment]
Possible heuristic change: determine which side of the equality is tight (perhaps just recently/locally), and only include that one.

**Comment by bqpd** [comment]
cvxopt will solve `Model(1/x, [x >= 0.1, y >= 1e-14, 1 >= x + y]).solve()` for any min/max of x/y

**Comment by bqpd** [comment]
More promisingly, `m = Model(x, [x >= 0.1, 1 <= x + y])` works with all solvers.

**Comment by bqpd** [comment]
More concrete proposal: 
  1. Choose half of the eq constraint to drop (the half which doesn't leave the problem unbounded?)
  2. Start SP solve
  3. If that half of the eq constraint ever becomes loose, switch which half you consider?

**Comment by whoburg** [comment]
It's fun plotting the MWE to visualize the constraint sets. The signomial equality constraint is the blue line. `x >= 0.1` is everything above the green line.

![signomial_equality](https://cloud.githubusercontent.com/assets/6042395/9792341/a37dec6a-57ad-11e5-87f6-a1c6ac13aa75.png)

I agree we need to address this with a heuristic change, but I don't think I'm ready to settle on a proposal yet -- need to deeply understand what's going wrong here, and worried about over-fitting our response to this example.

**Comment by whoburg** [comment]
In this case, dropping ALL signomial constraints (i.e. `x + y >= 1` in this example), doing a GP solve, and using that as the initial guess would work. But it's unclear to me whether that's the right approach in general.

**Comment by bqpd** [comment]
That's true. I think the existence of these "cycles" where only one point is valid may be something to look out for, as well as the problem of equality constraints leading to very very slow solver motion.

**Comment by bqpd** [comment]
@whoburg and I discussed a fix to this version of the SP equality problem (where only one side of the equality constraint is needed), which I'll hopefully test soon...

**Comment by whoburg** [comment]
Note for our group members that @pgkirsch did some writing on SP heuristics in our pubs repo -- worth checking out!

**Comment by bqpd** [comment]
Closing as an example of SP equality fun re #397
