### ISSUE TITLE
CVXOPT has difficulty solving problems where feasible set is a single point

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#403]
Can someone explain to me why this returns UNKNOWN?

Am I missing something?

```python
from gpkit.shortcuts import *

x0 = Var('x0')
x = Var('x')
y = Var('y')
M = 100

m = Model(x0,
         [x + M <= x0,
          0.1*x**-1 <= 1,
          x + y <= 1,
          2**(-0.5)*x**(-0.25)*y**(-0.25) <= 1])

m.solve()

# Output
# RuntimeWarning: final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.
```

I believe `x = y = 0.5` should be a valid solution.

**Comment by pgkirsch** [comment]
![plot]
(~/Desktop/plotissuepng)

**Comment by whoburg** [comment]
hmm, that's indeed surprising. Here's an equivalent version of the problem that I find easier to intuit:

```python
from gpkit.shortcuts import *

x0 = Var('x0')
x = Var('x')
y = Var('y')
M = 100

m = Model(x0,
         [x + M <= x0,
          0.1 <= x,
          x + y <= 1,
          .25 <= x*y])

m.solve()
```

cvxopt also says unknown.

**Comment by whoburg** [comment]
Still fails even removing the `0.1 <= x`:

```python
from gpkit.shortcuts import *

x0 = Var('x0')
x = Var('x')
y = Var('y')
M = 100

m = Model(x0,
         [x + M <= x0,
          x + y <= 1,
          .25 <= x*y])

m.solve()
```

**Comment by whoburg** [comment]
mosek solves all of these fine for me. But cvxopt fails on all of them.

**Comment by pgkirsch** [comment]
Mosek solves the first one for you?

**Comment by whoburg** [comment]
that's correct, mosek solves all three for me.

**Comment by whoburg** [comment]
@pgkirsch, it fails for you?? do the unit tests run for you?

**Comment by pgkirsch** [comment]
All 3 fail for me. Wait what?? 123 unit tests are failing and I just pulled... what on earth?

**Comment by whoburg** [comment]
is your mosek license expired?

**Comment by pgkirsch** [comment]
Oh yeah it expired yesterday

**Comment by whoburg** [comment]
Hmph!! Mosek and cvxopt both fail for me on this even simpler MWE:

```python
from gpkit.shortcuts import *

x = Var('x')
y = Var('y')

m = Model(x,
         [x + y <= 1,
          .25 <= x*y])

m.solve()
```

**Comment by whoburg** [comment]
Taking minimalistic to the extreme, cvxopt and mosek both return unknown on this:

```python
from gpkit.shortcuts import *

x = Var('x')

m = Model(x,
         [x + .25/x <= 1])

m.solve("cvxopt")
```

**Comment by bqpd** [comment]
Is `x = 0.5` the only valid solution to that?

**Comment by whoburg** [comment]
yeah, I think the feasible set is a single point, that might be part of the problem (though I'm a little vexed that neither solver would find that point).

**Comment by whoburg** [comment]
and cvxopt solves the original if you slack the `x + y <= 1` constraint.

**Comment by bqpd** [comment]
This is just a cvxopt issue, right?

**Comment by bqpd** [comment]
If so, the todo would seem to be raising the issue with them...

**Comment by whoburg** [comment]
cvxopt and mosek both return unknown on this: 

```python
from gpkit.shortcuts import *
x = Var('x')
m = Model(x, [x + .25/x <= 1])
m.solve("cvxopt")
```

We need to decide whether we think that's acceptable behavior. It's infinitesimally close to being infeasible; so perhaps not worth worrying about.

**Comment by whoburg** [comment]
Before complaining to the solver-writers, we should ask ourselves what we would want the dual solution to be...

**Comment by bqpd** [comment]
Sensitivity of >1 to the second posynomial, implying an x variable sensitivity of...1...oh dear.

**Comment by whoburg** [comment]
I'm pretty sure that if the second constraint is formulated as `x + .25/x <= s`, where `s` is a specified constant, then the sensitivity to that posynomial approaches infinity in the limit as s approaches 1 from above. You can see this by running a simple experiment setting `s` to 1.01, 1.001, 1.0001, etc, and looking at that sensitivity.

I'm not surprised that the solvers have problems when `s==1`; I support closing this unless anyone objects.

**Comment by bqpd** [comment]
Sounds good to me.

**Comment by whoburg** [comment]
@pgkirsch, this was originally opened by you; could you read it over and close if you agree?

**Comment by pgkirsch** [comment]
Ok sounds good. closing.

**Comment by whoburg** [comment]
Related to #428, in the sense of confusing solver output for modelers.
