### ISSUE TITLE
Installation Permission Denied 

### ISSUE THREAD

**Issue by mjburton11** [convexopt/gpkit#404]
While trying to install gpkit I received a "permission denied" error.  This may be a problem with how the securities are set up on my computer even though I am running from an administrator account.  Even though it is probably a system problem and not a gpkit bug it still might be good to have some documentation on it.  This was the error: 

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-762.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

**Comment by bqpd** [comment]
What commands did you run? It looks like your commands were using the system python and pip instead of the Anaconda versions.

If you have numpy and scipy installed system-wide, you could install gpkit with `sudo pip install gpkit`.

**Comment by mjburton11** [comment]
Oh ok that would make sense.  The command I used was:

python setup.py install

Ill try the sudo pip... command and see what happens.

Thanks!

On Mon, Sep 14, 2015 at 10:00 AM, bqpd <notifications@github.com> wrote:

> What commands did you run? It looks like your commands were using the
> system python and pip instead of the Anaconda versions.
>
> If you have numpy and scipy installed system-wide, you could install gpkit
> with sudo pip install gpkit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/convexopt/gpkit/issues/404#issuecomment-140084505>.
>



-- 
*Michael Burton*
*mjburton@mit.edu <mjburton@mit.edu>*
801-647-0021
MIT Aero/Astro Engineering
Class of 2016

**Comment by mjburton11** [comment]
Ok I just tried the sudo pip install gpkit and this is the error I got: 

Michaels-MacBook-Pro:cvxopt-1.1.7 mjburton11$ sudo pip install gpkit

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:
sudo: pip: command not found

**Comment by bqpd** [comment]
Okay, so it looks like pip is not installed on your system. Have you installed numpy and scipy? If not, you may wish to install Anaconda, as per http://gpkit.readthedocs.org/en/latest/installation.html#mac-os-x

**Comment by bqpd** [comment]
If you don't wish to install Anaconda, try `python gpkit/build.py`

**Comment by whoburg** [comment]
@mjburton11, it would be helpful if you can let us know at exactly what step in the installation instructions (http://gpkit.readthedocs.org/en/latest/installation.html) things started diverging / going wrong for you.

**Comment by bqpd** [comment]
(in honor of the issue number, I'm tempted to dub this "#404: Permissions not found"

**Comment by whoburg** [comment]
what's the status of this?

**Comment by bqpd** [comment]
@mjburton11 and I will meet today or tomorrow to figure it out

**Comment by bqpd** [comment]
Resolved by reinstalling Anaconda
