### ISSUE TITLE
Model setup should allow substitutions, like Model init

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#411]

**Comment by bqpd** [comment]
I'm actually beginning to think that it shouldn't. If anything, it should accept just straight Models (and pull the cost and constraints out) but I'm not sure of that either...I'll sit on this and see if anyone else brings it up.

**Comment by whoburg** [comment]
yeah, I don't have use case yet -- because I can always pass subs directly to the `Model` constructor, right? Would a user ever be calling `setup()` directly?

**Comment by bqpd** [comment]
Naw, but I think that people should be able to just turn their scripts into proper Object Models, so I added this functionality in in #430

**Comment by whoburg** [comment]
(closed by #430)
