### ISSUE TITLE
Examples output changes every time unit tests run

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#412]
It's a minor nuisance that `beam_output.txt` and `simple_box_output.txt` change whenever I run unit tests and therefore appear as unstaged changes in git. Is there any way we can change this without undermining the whole point of having examples that are part of the unit test framework?

**Comment by whoburg** [comment]
Which part changes? Timing information?

**Comment by whoburg** [comment]
Hmm, it doesn't change for me on master...

**Comment by pgkirsch** [comment]
```
[philippekirschen@dhcp-18-189-116-130 gpkit]$ git diff ../docs/source/examples/beam_output.txt 
diff --git a/docs/source/examples/beam_output.txt b/docs/source/examples/beam_output.txt
index 7f9521e..ed0d88f 100644
--- a/docs/source/examples/beam_output.txt
+++ b/docs/source/examples/beam_output.txt
@@ -1,7 +1,7 @@
 
 Cost
 ----
- 0.7813 [m] 
+ 0.7812 [m] 
 
 Free Variables
 --------------
```

**Comment by pgkirsch** [comment]
```
[philippekirschen@dhcp-18-189-116-130 gpkit]$ git diff ../docs/source/examples/simple_box_output.txt 
diff --git a/docs/source/examples/simple_box_output.txt b/docs/source/examples/simple_box_output.txt
index ae184ba..1cbc809 100644
--- a/docs/source/examples/simple_box_output.txt
+++ b/docs/source/examples/simple_box_output.txt
@@ -5,9 +5,9 @@ Cost
 
 Free Variables
 --------------
-d : 8.17   [m] depth 
-h : 8.163  [m] height
-w : 4.081  [m] width 
+d : 8.166  [m] depth 
+h : 8.164  [m] height
+w : 4.082  [m] width 
 
 Constants
 ---------
```

**Comment by whoburg** [comment]
Ahh! It must be because mosek and cvxopt give slightly different results (within numerical tolerance), and you only have one of the two solvers installed, correct?

**Comment by pgkirsch** [comment]
No I have both solvers installed these days

**Comment by bqpd** [comment]
What's your default solver?

**Comment by bqpd** [comment]
(also, if you pull #391 does it have the same issue?)

**Comment by pgkirsch** [comment]
1. Mosek
2. yes

**Comment by whoburg** [comment]
So, this can be explained by the fact that @pgkirsch has a different default solver than everyone else, correct?

**Comment by bqpd** [comment]
Yup!

**Comment by whoburg** [comment]
@pgkirsch, any reason not to switch your default solver back? That would resolve this.

**Comment by bqpd** [comment]
CVXopt is also not working right now on El Capitan + Anaconda...

**Comment by pgkirsch** [comment]
Happy to switch it back once I have a working cvxopt. In fact, it wasn't that I changed the default solver but that cvxopt, though installed and working, did not appear as one of my installed solvers for the previous anaconda/ipython-only mess that was my environment.
