### ISSUE TITLE
Mixed-integer GP example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#413]
Some colleagues are working on a new solver which is capable of handling MIDCP (mixed-integer disciplined convex, a la CVX) problems. Through the magic of the exponential cone, this means that they could also handle mixed-integer geometric programming problems.

Would be great to come up with some mixed-integer GP examples we're interested in solving, and have GPkit dump out the solver-format description (c, A, map, etc) for them to try their solver on.

In case anyone's wondering, they're not ready to hook into GPkit just yet -- their solver is still experimental / in development.

**Comment by cjk12** [comment]
I may have some stuff here.  A good one would be number of engines on a
really basic aircraft model, but perhaps you're looking for simpler
problems at first.

On Thu, Oct 1, 2015 at 10:52 AM, Warren Hoburg <notifications@github.com>
wrote:

> Some colleagues are working on a new solver which is capable of handling
> MIDCP (mixed-integer disciplined convex, a la CVX) problems. Through the
> magic of the exponential cone, this means that they could also handle
> mixed-integer geometric programming problems.
>
> Would be great to come up with some mixed-integer GP examples we're
> interested in solving, and have GPkit dump out the solver-format
> description (c, A, map, etc) for them to try their solver on.
>
> In case anyone's wondering, they're not ready to hook into GPkit just yet
> -- their solver is still experimental / in development.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/convexopt/gpkit/issues/413>.
>



-- 
*Cody J. Karcher*
Graduate Student
Massachusetts Institute of Technology
Department of Aeronautics and Astronautics
International Center for Air Transportation

**Comment by whoburg** [comment]
Yeah! I figured a lot of configuration choices are representable as integer variables.

**Comment by cjk12** [comment]
Yes, this goes really well with the new direction I'm thinking too.  Let me
put something together for you.

On Thu, Oct 1, 2015 at 11:19 AM, Warren Hoburg <notifications@github.com>
wrote:

> Yeah! I figured a lot of configuration choices are representable as
> integer variables.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/convexopt/gpkit/issues/413#issuecomment-144760417>.
>



-- 
*Cody J. Karcher*
Graduate Student
Massachusetts Institute of Technology
Department of Aeronautics and Astronautics
International Center for Air Transportation

**Comment by whoburg** [comment]
This is a really good read and highly suggested for getting in the mindset of modeling with integer variables: http://web.mit.edu/15.053/www/AMP-Chapter-09.pdf

**Comment by bqpd** [comment]
See also #58

**Comment by bqpd** [comment]
Should this be in the gpkit-model repo?

**Comment by whoburg** [comment]
sure, and #414 can stick around to implement the GPkit side of things

**Comment by bqpd** [comment]
Moved!
