### ISSUE TITLE
El Capitan ruins everything

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#416]
Causes 40 errors in unit tests (on master)

```
ImportError: Could not load MOSEK library: ImportError(OSError('dlopen(/Users/philippekirschen/.gpkit/expopt.so, 10): Library not loaded: @loader_path/libmosek64.7.0.dylib\n  Referenced from: /Users/philippekirschen/.gpkit/expopt.so\n  Reason: image not found',),)
```

Will post fix if/when I find it...

**Comment by bqpd** [comment]
Noooooooo (not too surprised)

**Comment by bqpd** [comment]
Does `mosek_cli` work?

**Comment by pgkirsch** [comment]
Yes `mosek_cli` works

**Comment by whoburg** [comment]
Do we think this has to do with the install script? This is high priority...

**Comment by pgkirsch** [comment]
Good news: this might not be a gpkit issue at all. Running the cvxopt installation test (`$CVXOPT/examples/doc/chap8/lp.py`) works with python but doesn't work with ipython and the error smells like the error when I get run the unit tests (with ipython):
```
[philippekirschen@kirschens-macbook-pro chap8]$ python lp.py
     pcost       dcost       gap    pres   dres   k/t
 0: -8.1000e+00 -1.8300e+01  4e+00  0e+00  8e-01  1e+00
 1: -8.8055e+00 -9.4357e+00  2e-01  3e-16  4e-02  3e-02
 2: -8.9981e+00 -9.0049e+00  2e-03  2e-16  5e-04  4e-04
 3: -9.0000e+00 -9.0000e+00  2e-05  1e-16  5e-06  4e-06
 4: -9.0000e+00 -9.0000e+00  2e-07  2e-16  5e-08  4e-08
Optimal solution found.

x = 

[ 1.00e+00]
[ 1.00e+00]

[philippekirschen@kirschens-macbook-pro chap8]$ ipython lp.py 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/philippekirschen/Documents/MIT/Research/GPkit/cvxopt-1.1.7/examples/doc/chap8/lp.py in <module>()
      1 # The small LP of section 8.3 (Linear programming).
      2 
----> 3 from cvxopt import matrix, solvers
      4 c = matrix([-4., -5.])
      5 G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])

//anaconda/lib/python2.7/site-packages/cvxopt-1.1.7-py2.7-macosx-10.5-x86_64.egg/cvxopt/__init__.pyc in <module>()
    253     exp, log
    254 
--> 255 from cvxopt import solvers, blas, lapack
    256 
    257 __all__ = [ 'blas', 'lapack', 'amd', 'umfpack', 'cholmod', 'solvers',

/Users/philippekirschen/Documents/MIT/Research/GPkit/cvxopt-1.1.7/examples/doc/chap8/build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py in <module>()

/Users/philippekirschen/Documents/MIT/Research/GPkit/cvxopt-1.1.7/examples/doc/chap8/build/bdist.macosx-10.5-x86_64/egg/cvxopt/lapack.py in __bootstrap__()

ImportError: dlopen(/Users/philippekirschen/.python-eggs/cvxopt-1.1.7-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so, 2): Symbol not found: _dgesv_
  Referenced from: /Users/philippekirschen/.python-eggs/cvxopt-1.1.7-py2.7-macosx-10.5-x86_64.egg-tmp/cvxopt/lapack.so
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
```

**Comment by pgkirsch** [comment]
Now I'm confused.

As mentioned above, I ran unit tests and failed 40 (out of 123) for mosek and 38 out of 123. I did this again just half an hour ago after trying some things.

Then I did `pip install gpkit --upgrade` for giggles.

Then I pulled from the repo (all on master) for giggles.

Now, I execute `ipython tests/run_tests.py` and I pass all unit tests except now there are only 93 unit tests. What have I done?

**Comment by whoburg** [comment]
I'll make a couple comments on the above though I'm sure @bqpd will have more ideas.

1. Not knowing what `pip install --upgrade` does, to get all unit tests I'd suggest pulling the latest from the repo and running `python setup.py install` in whatever virtual environment you want to install into (or system-wide, if you like). (I agree the pip version should also work; this is just intended to help with debugging the 93 vs 123 unit tests issue).

2. Note you can run `./runtests.sh` in the gpkit directory to debug the python vs. ipython issues. runtests.sh relies only on python, not ipython.

**Comment by pgkirsch** [comment]
Because of my personal setup (which admittedly I don't fully understand), when I run `python setup.py install` and `ipython setup.py install` I get very different results. Python finds cvxopt and mosek_cli whereas ipython finds mosek and mosek_cli. Python also doesn't seems to have permission to write to `/Library`: 

`error: could not create '/Library/Python/2.7/site-packages/gpkit': Permission denied`

So, i ran `ipython setup.py install` and that gave me 113 tests and 34 errors.

Then I ran `./runtests.sh` and that gave me 125 tests and 43 errors.

**Comment by pgkirsch** [comment]
Obviously `sudo python setup.py install` solved my permission issue, and now I get 125 tests, 8 errors,
 but now all of these errors are

```
TypeError: unsupported operand type(s) for <some operand>: 'int' and 'PosyArray'
```

**Comment by pgkirsch** [comment]
(I'm basically just making notes for myself here)

As a (poor) surrogate for setting up virtual environments I moved anaconda further back on my path a while ago so that `python` calls my system installation version of python instead of the anaconda version. This likely helps explain a lot, if not all, of the differences in behaviour between `python` and `ipython`.

I am considering deleting/uninstalling everything (solvers, anaconda, gpkit) and starting from scratch with proper virtualenv stuff (and I know that's what @whoburg would prefer me to do) but first I want to figure out what the full consequences of that would be and if it's worth it, or if I can just figure this out some other way.

**Comment by bqpd** [comment]
I suspect that your iPython and Python executables are in different directories...I'd even go further and  speculate that only iPython is Anaconda.

**Comment by pgkirsch** [comment]
It appears that reinstalling anaconda has resolved the issues.

**Comment by bqpd** [comment]
Yay!

**Comment by pgkirsch** [comment]
`python setup.py install` (both python and ipython now I have reinstalled anaconda and it is back at the front of my path) still gives me the error:

```
OSError: [Errno 13] Permission denied: 'gpkit/env/settings'
```

**Comment by bqpd** [comment]
huh...

**Comment by pgkirsch** [comment]
just to be clear the line of `build.py` that is triggering the error is:

```python
/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/build.pyc in replacedir(path)
     33     log("#     Replacing directory", path)
     34     if os.path.isdir(path):
---> 35         shutil.rmtree(path)
     36     os.makedirs(path)
     37     return path
```

where `path` is `gpkit/env`.

**Comment by bqpd** [comment]
My suspicion is that the permissions on that dir got strangely set at some point...

**Comment by pgkirsch** [comment]
Uninstall and reinstall?

**Comment by bqpd** [comment]
I want to take a look and confirm...maybe at 3pmish, if that works for you?

**Comment by pgkirsch** [comment]
Works for me. The dir permissions look fine at first inspection btw. Also, this probably doesn't tell you much, but `sudo python setup.py install` obviously works fine.

**Comment by pgkirsch** [comment]
(More notes for myself)
Current status:

_Working:_
- All 125 unit tests pass (using `mosek`, `mosek_cli`) 
- `import mosek`
- `python ~/mosek/..../lo1.py`


_Not working:_
(Each of the following generates some sort of dynamic library error)
- `import cvxopt` (others having the same issue https://groups.google.com/forum/#!topic/cvxpy/7KXcBnunR_Y)
- `python ~/cvxopt/.../lp.py1
- `python some_gp.py`, where `some_gp.py` is a script file that solves a GP.

**Comment by pgkirsch** [comment]
I think I'm losing my mind.

Now unit tests are failing again.

**Comment by pgkirsch** [comment]
...but only when I call `python run_tests`. 

`./runtests.sh` still works fine.

**Comment by bqpd** [comment]
This just in: El Capitan is the worst, doesn't support `DYLD_LIBRARY_PATH` for subprocesses, so we'll need to figure out a new way to link mosek_64.dylib. Also, @pgkirsch, could you link to the cvxopt issue you created?

**Comment by pgkirsch** [comment]
Issue opened on cvxopt github page: https://github.com/cvxopt/cvxopt/issues/45

**Comment by whoburg** [comment]
El Capitan is the worst, but you guys are the best -- thanks for working to get to the bottom of this.

**Comment by pgkirsch** [comment]
With "mosek_cli" as the only installed solver in `env/settings`, my unit tests all pass, but my scripts return the following:

```
CalledProcessError                        Traceback (most recent call last)
/Users/philippekirschen/Documents/MIT/Hyperloop/Design/GP/americium.py in <module>()
     66              )
     67 
---> 68     sol = m.localsolve()
     69 
     70 

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/model.py in localsolve(self, solver, verbosity, skipfailures, *args, **kwargs)
    246                 print solver
    247                 return self._solve("sp", solver, verbosity, skipfailures,
--> 248                                    *args, **kwargs)
    249         except ValueError as err:
    250             if err.message == ("SignomialPrograms must contain at least one"

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/model.py in _solve(self, programType, solver, verbosity, skipfailures, *args, **kwargs)
    349             self.program, solvefn = form_program(programType, signomials,
    350                                                  verbosity=verbosity-1)
--> 351             result = solvefn(*args, **kwargs)
    352             solution.append(parse_result(result, constants, beforesubs))
    353         solution.program = self.program

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/signomial_program.pyc in localsolve(self, solver, verbosity, x0, rel_tol, iteration_limit, *args, **kwargs)
    122                 nearest_feasible = feasibility_model(gp, "max")
    123                 self.gps.append(nearest_feasible)
--> 124                 result = nearest_feasible.solve(verbosity=verbosity-1)
    125                 result["cost"] = None
    126             x0 = result["variables"]

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/geometric_program.pyc in solve(self, solver, verbosity, *args, **kwargs)
    135             sys.stdout = self.solver_log   # CAPTURING STDOUT
    136             solver_out = solverfn(c=self.cs, A=self.A, p_idxs=self.p_idxs,
--> 137                                   k=self.k, *args, **kwargs)
    138         finally:
    139             sys.stdout = original_stdout   # RETURNING STDOUT

/Users/philippekirschen/Documents/MIT/Research/GPkit/gpkit/gpkit/_mosek/cli_expopt.pyc in imize(c, A, p_idxs, *args, **kwargs)
    101                           for x in t_j_Atj])
    102 
--> 103         log = check_output(["mskexpopt", filename])
    104         for logline in log.split(b"\n"):
    105             print(logline)

/Users/philippekirschen/anaconda/lib/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    571         if cmd is None:
    572             cmd = popenargs[0]
--> 573         raise CalledProcessError(retcode, cmd, output=output)
    574     return output
    575 

CalledProcessError: Command '['mskexpopt', '/var/folders/37/69lsg4fs3pxcslvp2pgg82th0000gr/T/tmpUlKxDM/gpkit_mosek']' returned non-zero exit status 152
```

Do I need to do anything different to get it to run with `mosek_cli`? At the moment solver is `None`, even if I set `solver="mosek_cli"`.

**Comment by pgkirsch** [comment]
Response from mosek:

> Erling D. Andersen (Mosek Aps)
Oct 6, 07:01

Yes, it seems that OSX is getting rid of DYLD_LIBRARY_PATH. For that reason the default MOSEK installation does not require it.
One way to solve the issue you have is to use

install_name_tool

Google for instance

install_name_tool rpath

and something like

https://blogs.oracle.com/dipol/entry/dynamic_libraries_rpath_and_mac

maybe then tell what to do.

Below is also what we have in our internal wiki.

OS X/Mach-O

OS X uses the Mach-O executable format.
Useful tools on OS X:
ld is the linker.
otool is a tool that does the jobs of ldd, nm, objdump etc. Specifically, otool -L ... prints the library dependencies.
install_name_tool can edit some properties of Mach-O binaries, not least edit library name dependencies.
When a binary executable has been built, the library names can be changed using the install_name_tool
Example
Consider the example
libtest/
libtest/test.c # refers to a function in liba
libtest/A/liba.c # refers to a function in libb
libtest/B/liba.c
And we build it all:
gcc -shared -o libtest/B/libb.so libtest/B/libb.c
gcc -shared -o libtest/A/liba.so libtest/A/liba.c -Llibtest/B -lb
gcc -o libtest/test -Llibtest/A -la libtest/test.c
Now otool will tell that test depends on </tt>liba.so</tt>, and liba.so depends on libb.so. Running libtest/test will fail because the runtime linker cannot find liba, but setting DYLD_LIBRARY_PATH=libtest/A:libtest/B and running again will succeed.
We now do:
install_name_tool -change @executable_path/A/liba.so libtest/test liba.so
install_name_tool -change @executable_path/B/libb.so libtest/A/liba.so libb.so
Running the example without setting DYLD_LIBRARY_PATH will now succeed.
We now do:
install_name_tool -change @executable_path/A/liba.so @loader_path/A/liba.so libtest/test
install_name_tool -change @executable_path/B/libb.so @loader_path/../B/libb.so libtest/A/liba.so
Running the example without setting DYLD_LIBRARY_PATH will now succeed.
When changing the library names, following run-time substitutions apply:
@executable_path
For both libraries and executables, this is replaces with the path to the executable file, as demonstrated in the first case above.
@loader_path
For both libraries and executables, this is replaces with the path to the binary object in which it is specified, as demonstrated in the second case above. In programs it is replaced by the path to the executable, in libraries by the path to the library.
@rpath
In this case the paths specified with -rpath at link-time (or later with install_name_tool) are searched.
Debugging tips
Show the install name:
otool -D mylib.dylib
Show the dependencies:
otool -L mylib.dylib
Change the path in a library:
$ install_name_tool -change /opt/intel/cc/10.1.009/lib/libintlc.dylib libintlc.dylib libimf.dylib
$ otool -L libimf.dylib
libimf.dylib:
libimf.dylib (compatibility version 0.0.0, current version 0.0.0)
libintlc.dylib (compatibility version 0.0.0, current version 0.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 88.3.9)
Turn on library loading debug output:
export DYLD_PRINT_LIBRARIES=1

Regards

Erling

**Comment by galbramc** [comment]
I've added an El Capitan testing machine for the pull request builds. Let me know when you want me to add it to pushes as well.

Let me know if you need any help with the install_name stuff. I'm not an expert, but I'm starting to get a better understand of how it works. It's the most awkward thing I have ever heard of though.

**Comment by whoburg** [comment]
(Background for those following this thread): @galbramc knows how to use install_name as a substitute for DYLD_LIBRARY_PATH, which apple has apparently done away with. Need someone to take charge of making us El Capitan - compatible, and/or keep track of any external solver issues that prevent that.
