### ISSUE TITLE
clean up simpleflight example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#420]
At the very least, I think we can remove the `if gpkit.units` conditional, by defining the `8.71e-5` and `45.24` as constants (Variables with units).

**Comment by whoburg** [comment]
It's the simple wing example here: http://gpkit.readthedocs.org/en/latest/examples.html

**Comment by mjburton11** [comment]
Hey I just finished editing the simpleflight.py example file and confirmed that it works.  However, it didn't let me push it through.  It says: Permission to convexopt/gpkit.git denied to mjburton11.
fatal: unable to access 'https://github.com/convexopt/gpkit.git/': The requested URL returned error: 403

**Comment by bqpd** [comment]
This has been pulled, right?

**Comment by whoburg** [comment]
yep, #423
