### ISSUE TITLE
Fuel example is out of date

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#422]
Didn't get updated after Model/GP switch

**Comment by whoburg** [comment]
@tonystao

**Comment by bqpd** [comment]
(also should be updated w/ working interactives...)

**Comment by bqpd** [comment]
Shoot everything's changed in iPython widgets. They're not even bundled by default anymore???

**Comment by pgkirsch** [comment]
This example only exists as an ipython notebook at the moment, correct?

**Comment by bqpd** [comment]
Yup.

**Comment by whoburg** [comment]
Working Fuel example is currently living here: http://nbviewer.ipython.org/github/convexopt/gpkit/blob/master/docs/source/ipynb/Fuel/Fuel.ipynb.

This may change.
