### ISSUE TITLE
Update Modular example

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#425]
The modular example is currently out of date -- `docs/source/ipynb/modular/modular.ipynb` still inherits from GP instead of Model. Is this the best example we have of what will ultimately become Models playing together?

**Comment by bqpd** [comment]
Yeah, I made that to get some feedback at the time and it didn't go anywhere.

**Comment by bqpd** [comment]
Closing this as per the recent meeting and new PR.

**Comment by whoburg** [comment]
But I don't think that addresses `docs/source/ipynb/modular/modular.ipynb` -- are we deleting it or updating it? delete?

**Comment by bqpd** [comment]
Hmm, I'll update it.

**Comment by whoburg** [comment]
should we call the issue "document modularity"? I'd love to see it moved from an ipynb to a more prominent section of the docs

**Comment by bqpd** [comment]
That should definitely happen, but how about a new issue?

**Comment by whoburg** [comment]
Sure that works great, but sorry, I'm confused. There are 3 things in play:

1. making models modular / making models play together
2. Updating `docs/source/ipynb/modular/modular.ipynb`
3. More general documentation of modular models

The title of this ticket corresponds to 1. but the content corresponds to 2., and I don't think 3. is covered anywhere yet. Does it make sense to do the following for the above items?

1. (covered by #429 )
2. this issue -- rename to "update modular example"
3. open new issue

**Comment by bqpd** [comment]
3 is mentioned in the checklist issue, though not in-depth.

**Comment by whoburg** [comment]
Is there value in keeping the Fuel example around? It seems like a duplicate of Modular, and modular seems better.

**Comment by bqpd** [comment]
Fuel is still faster, and has interactives (which Model could, but does not). So no good reasons, but some reasons.

**Comment by whoburg** [comment]
Ok, understood -- we'll leave it for now then, with an aim for fixing #479 and eventually adding interactives to modular.
