### ISSUE TITLE
Ordered results tables

### ISSUE THREAD

**Issue by pgkirsch** [convexopt/gpkit#458]
I know results tables are written from dicts, but if there were a way to print the Variable and Constant tables in alphabetical order, and the Sensitivity table in the order of descending magnitude, I think it would be a really cool enhancement!

It's getting a bit tricky to find the value I'm looking for as my programs get to be a little bigger.

**Comment by bqpd** [comment]
Great idea! This should be totally doable.

**Comment by bqpd** [comment]
I'm inclined to have model_name always be first priority, then sens/name?

**Comment by whoburg** [comment]
@bqpd, that clearly makes sense for the Variable table; for the sensitivity table I can imagine wanting things grouped by model or grouped by sensitivity. Suppose we could have separate "top 10 sensitivities" table, though I cringe somewhat at even suggesting duplicate output...

**Comment by pgkirsch** [comment]
Grouping by sub-model for the variables and constants seems like a natural choice. For sensitivities I would vote for ordering purely by sensitivity. Agree with @whoburg about not wanting to duplicate output.

**Comment by bqpd** [comment]
Heh, sounds good.

**Comment by pgkirsch** [comment]
Is there any chance of getting this done today?

**Comment by bqpd** [comment]
This was done in` tables_newcontsrs`.

**Comment by whoburg** [comment]
`tables_newcontsrs` is not in any current PR's; is it not ready for prime time yet?

**Comment by bqpd** [comment]
Yeah, cause it has `newconstrs`; but I was making a note to myself that the last two commits, with minor adaptation, could be cherry-picked to close this!
