### ISSUE TITLE
Numpy 1.10

### ISSUE THREAD

**Issue by galbramc** [convexopt/gpkit#464]
gpkit does not work with numpy 1.10

**Comment by whoburg** [comment]
@bqpd, let's update the docs for now to state the known issue and have anaconda install an earlier numpy version?

**Comment by bqpd** [comment]
Good plan. (you mean pip/ the "requires" flag in setup.py?)

**Comment by whoburg** [comment]
Good point -- yes, that. Additionally, do we need to update the Anaconda setup instructions (http://gpkit.readthedocs.org/en/latest/installation.html) to have virtual environments use the right version of numpy?

**Comment by bqpd** [comment]
I think I just want to get it working in both versions rather than doing that. :p

**Comment by bqpd** [comment]
(installing numpy 1.10 now)

**Comment by whoburg** [comment]
that works too.  :)

**Comment by whoburg** [comment]
I'm starting to see why people complain about managing dependencies  :/

**Comment by galbramc** [comment]
Ironically, the person we know who complains the most about dependencies
writes code that becomes a dependency for others :P

**Comment by whoburg** [comment]
who, me?

**Comment by galbramc** [comment]
No, the loud guy who sits next to me.

**Comment by galbramc** [comment]
I updated numpy on El Cap to numpy 1.10. Seems to be working.
