### ISSUE TITLE
Standardization of default values for Model setup

### ISSUE THREAD

**Issue by whoburg** [convexopt/gpkit#472]
@bqpd and I agreed in person on the following best practices

 - the kwargs of Model `setup` methods should not generally be used to encode default values
 - Default values should be placed in the `value` kwarg of `Variable()`
 - If a different substitution is desired, this should be passed as a string substitution to `Model.__init__()`.

What is needed to close this issue is 

 - [ ] adding a substitutions arg to `Model.__init__` (stop catching it)
 - [x] Need working example of best practices for the docs (perhaps modify the Troposphere model? edit: Breguet instead.).

**Comment by bqpd** [comment]
The troposhere model actually needs those as raw numbers, since they're in the exponent, but I updated the breguet range model for an example.

**Comment by whoburg** [comment]
breguet update looks good!

**Comment by whoburg** [comment]
we can check off the first check box, correct?

**Comment by bqpd** [comment]
yup!
