### ISSUE TITLE
docstring everything

### ISSUE THREAD

**Issue by bqpd** [convexopt/gpkit#78]
They should have them!

And while I'm of the opinion that explanatory names are better than inline comments, we could certainly use more of both...

**Comment by bqpd** [comment]
This is even more true now that the glossary is up! @convexopt/developers, shall we find a few high-value targets to document in the [glossary](http://gpkit.readthedocs.org/en/latest/glossary.html)?

**Comment by whoburg** [comment]
Removing milestone 0.1.0 tag. We still need better documentation on several classes, including closing out TODO items.

**Comment by bqpd** [comment]
Should this be split into subissues?

**Comment by bqpd** [comment]
Closing this issue because it doesn't seem to serve much purpose.

**Comment by whoburg** [comment]
I'll open some sub-issues now. Everyone please open issues if you run into insufficient documentation while using gpkit.
